"""Large offline Speaking bank: exactly 700 Part 1, 600 Part 2 and 800 Part 3 items.

Part 1 = 7 categories x 100 real "introduction & interview" questions.
Part 2 = 6 cue-card categories x 25 cards x 4 "you should say" variants.
Part 3 = 8 discussion categories x 100 real examiner questions.
Numbering restarts from 1 in every part. Schema matches speaking_bank items.
"""

from typing import Any

Item = dict[str, Any]

_TIPS = {
    "Part 1": ["Answer directly, add a reason, and give one small example.", "Keep answers to 2-3 sentences - Part 1 is a conversation, not a lecture.", "Use natural connectors: 'actually', 'for example', 'the main reason is'."],
    "Part 2": ["Use the 4 prompt points as paragraph markers, and keep going for the full 2 minutes.", "Write 4 keywords in your one-minute preparation.", "Start with a clear topic sentence and finish with a personal feeling."],
    "Part 3": ["Give a clear claim first, then a reason and an example.", "If the question asks 'Why?', give causes and mention your own country.", "Answer the exact question that was asked."],
}

# ====================================================================
# PART 1 - 7 categories x 100. Question numbering restarts at 1 in Part 1.
# ====================================================================
_P1 = [
    ('Personal Information', [
        'Which room do you spend the most time in?',
        'Where is your hometown?',
        'Has your hometown changed much since you were a child?',
        'Is it a nice place for young people to live in?',
        'Would you recommend your hometown to tourists?',
        'Do you plan to live in your hometown for the rest of your life?',
        'Tell me a little about your family.',
        'Who are you closest to in your family?',
        'Do you have many friends?',
        'Are friends more important than relatives for people your age?',
        'What is the busiest part of your day?',
        'How many hours of sleep do you need to feel good?',
        'How much sleep do young people actually need?',
        'What would a perfect day off look like for you?',
        'Do the weekends feel too short?',
        'Do you plan your weekends in advance?',
        'Has the way you spend free time changed in recent years?',
        'What are your main hobbies?',
        'Do you and your friends share the same hobbies?',
        'Do children today play different games from the ones you played?',
        'Are wild animals protected well in your country?',
        'Do birds in cities cause any problems?',
        'Who does most of the cooking in your home?',
        'Has your breakfast changed over the years?',
        'Do people in your country drink tea as a social activity?',
        'What is the most popular dish in your country?',
        'Are people in your country careful about healthy food?',
        'Do you trust the quality of street food?',
        'Would you recommend street food to a visitor?',
        'Do you offer sweets to guests in your home?',
        'What snacks do you keep in your kitchen?',
        'Do you eat snacks between meals?',
        'Who does the grocery shopping in your home?',
        'Do you usually pay for things in cash or by card?',
        'Do you care about the clothes you wear?',
        'Do you follow fashion trends?',
        'For you, is comfort more important than style?',
        'What is the traditional outfit in your country?',
        'When do people wear traditional clothes?',
        'What are you saving up for at the moment?',
        'Did your parents teach you to save?',
        'Do young people in your country save enough?',
        'When do people in your country give gifts?',
        'Are birthdays a big event in your country?',
        'Would you organise a surprise party for somebody?',
        'How do people spend public holidays in your country?',
        'Do you travel during public holidays?',
        'What is the biggest celebration of the year in your country?',
        'Do you listen to music very often?',
        'What dances are traditional in your country?',
        'Is art more difficult than music?',
        'What do you take pictures of the most?',
        'What was the last book you finished?',
        'Is your handwriting easy to read?',
        'Did school teach you good handwriting?',
        'Do we lose something by not writing by hand?',
        'Do you type fast?',
        'Do you use shortcuts when you type?',
        'Do young people type more than they write?',
        'How easy is it to trust the news you see?',
        'Was there a news story that changed your mind?',
        'Do you read newspapers?',
        'Do young people in your country read newspapers?',
        'Do you rely on your phone very much?',
        'What do you use your phone for besides calls?',
        'Do you feel lost without your phone?',
        'Which app is a must-have on your phone?',
        'What do your friends use their apps for?',
        'Can an app be dangerous?',
        'Which platform do you open first in the morning?',
        'Do most of your friends use the same apps as you?',
        'Do you play video games?',
        'Are video games more popular than board games now?',
        'Do you find robots interesting?',
        'Where could robots be truly useful?',
        'Do you worry that AI changes the way some jobs work?',
        'Do you use AI tools for your studies?',
        'What do you use your computer for?',
        'Can you fix a computer problem yourself?',
        'Do you watch much television?',
        'Are you following any series at the moment?',
        'Do you watch films without subtitles when you travel?',
        'Do you walk very much?',
        'What is the most beautiful scenery in your country?',
        'Where can you have a good view of your city?',
        'Do you take photos of scenery?',
        'What makes a building beautiful?',
        'Are there parks near your home?',
        'What do people do in parks?',
        'How do parks help your neighbourhood?',
        'Do you keep plants at home?',
        'Do you give flowers to people?',
        'Is gardening becoming popular among young people?',
        'How much nature is left in your city?',
        'Has the weather changed in recent years?',
        'Do you check the weather app every morning?',
        'Do you notice big changes between the seasons?',
        'Does any season make your town busy?',
        'What does summer mean to you?',
        'Do you take summer holidays?',
    ]),
    ('Preferences', [
        'Do you live in a house or an apartment?',
        'Do you prefer living in a big home or a small one? Why?',
        'Do you work or are you a student?',
        'What do you enjoy most about your job or your studies?',
        'Is there anything about your job or studies that annoys you?',
        'Do you prefer a few close friends or a big group of friends?',
        'Are you an early riser or a night person?',
        'Do you watch TV or use your phone just before sleeping?',
        'When is your day off from work or study?',
        'Do you prefer a busy day off or a quiet one?',
        'Do you prefer spending free time alone or with people?',
        'Are you a cat person or a dog person?',
        'Do you prefer cooking for yourself or eating out?',
        'Do you eat breakfast at home or outside?',
        'Do you prefer tea or coffee?',
        'How do you take your tea or coffee?',
        'Do you prefer drinking at home or in a café?',
        'Do you prefer local dishes or foreign food?',
        'How do you choose a snack?',
        'Do you prefer big malls or small shops?',
        'If you had extra money, would you save it or spend it?',
        'Do you prefer practical gifts or surprising ones?',
        'Do you give handmade gifts or bought ones?',
        "Do you prefer celebrating your birthday or another person's?",
        'Do you like songs for the music or for the words?',
        'Do you ever sing in the shower or in the car?',
        'Do you like drawing or painting?',
        'Do you prefer your phone camera or a proper camera?',
        'Do you read paper books or e-books?',
        'Do you prefer typing or writing by hand?',
        'Do you prefer emails or hand-written letters?',
        'Do you type more on your phone or on a keyboard?',
        'Do you prefer local news or world news?',
        'Do you enjoy gaming alone or with friends?',
        'Do you prefer a desktop or a laptop?',
        'How do you choose what to watch?',
        'Do you watch one episode at a time or several?',
        'Do you prefer watching films at home or in the cinema?',
        'Do you walk to work or college often?',
        'Where in your city is your favorite walk?',
        'Which building in your hometown is your favourite?',
        'Do you prefer modern or historic buildings?',
        'Which season is your favourite?',
        'Do you prefer team sports or individual sports?',
        'Do you watch matches live at the stadium or at home?',
        'Do you prefer the sea or a pool?',
        'Do you prefer travelling alone or with others?',
        'Do you prefer the beach or the city during holidays?',
        'What is your favourite beach in your country?',
        'Do you prefer a deep sleep to a dream: full one?',
        'Do you sometimes work or study from home?',
        'Do you measure success by money or by happiness?',
        'Is happiness more about moments or about life goals?',
        'Do you prefer sweet or savoury food?',
        'Is your hair style simple or bold?',
        'Do you prefer keys or a code on your door?',
        'Do you collect anything now, for example stamps or postcards?',
        'Do you use notes or reminders on your phone?',
        'Do you prefer paper notes or alarms?',
        'Do you prefer calling or sending messages?',
        'When should you call instead of text?',
        'Do you prefer calling people or texting them?',
        'Do you have a car or a license?',
        'Do you prefer driving or using the bus?',
        'Do you like live music or recordings?',
        'Is it better to give money or time?',
        'Do some people prefer local villas?',
        'Do you buy shoes for comfort or looks?',
        'Do you eat cereal or something hot?',
        'Do you read more on paper or on a screen?',
        'Do you prefer to be busy or relaxed?',
        'Do you prefer texting or talking on the phone?',
        'Do you prefer living in the city centre or in the suburbs?',
        'Do you prefer studying in the morning or at night?',
        'Do you prefer taking notes on paper or on a laptop?',
        'Do you prefer group study or studying alone?',
        'Do you prefer your own room or sharing with someone?',
        'Do you prefer warm weather or cold weather?',
        'Do you prefer summer or winter holidays?',
        'Do you prefer relaxing holidays or active ones?',
        'Do you prefer staying with relatives or booking a hotel?',
        'Do you prefer seaside food or mountain food?',
        'Do you prefer breakfast in bed or at the table?',
        'Do you prefer cooking simple meals or complicated dishes?',
        'Do you prefer eating with chopsticks or a fork?',
        'Do you prefer sweet snacks or salty ones?',
        'Do you prefer coffee shops or tea houses?',
        'Do you prefer shopping online or in stores?',
        'Do you prefer window shopping or buying quickly?',
        'Do you prefer clothes that are fashionable or comfortable?',
        'Do you prefer bright colours or dark colours?',
        'Do you prefer short hair or long hair?',
        'Do you prefer talking to people face to face or online?',
        'Do you prefer meeting new people or staying with old friends?',
        'Do you prefer quiet evenings or lively ones?',
        'Do you prefer indoor or outdoor hobbies?',
        'Do you prefer a packed schedule or a free one?',
        'Do you prefer getting up early or sleeping in?',
        'Do you prefer planning things or doing them spontaneously?',
        'Do you prefer driving a car or taking the subway?',
    ]),
    ('Likes / Dislikes', [
        'Is there anything you would like to change about your home?',
        'Would you like to live in a different kind of home in the future?',
        'What do you like most about your hometown?',
        'Would you like to have a big family yourself one day?',
        'What do you like to do with your friends?',
        'Do you like getting up early in the morning?',
        'What do you like to do at weekends?',
        'Is there a hobby you would like to start?',
        'Do you like watching wild animals?',
        'Which wild animal would you most like to see one day?',
        'Would you like to work with animals?',
        'Do you like cooking?',
        'Do you enjoy trying new cuisines?',
        'What kind of street food do you like to eat?',
        'Do you like sweets and chocolate?',
        'Do you enjoy shopping?',
        'Do you like traditional clothes?',
        'Do you enjoy receiving gifts?',
        'Do you like giving presents?',
        'Which public holiday do you like this most?',
        'Do you enjoy big family celebrations?',
        'What kind of music do you enjoy the most?',
        'Do you like singing?',
        'Do you like dancing?',
        'What do you enjoy most about a museum?',
        'Do you like modern art?',
        'What would you like to see in a museum?',
        'Do you like taking photographs?',
        'Do you like reading?',
        'Which kind of books do you enjoy reading?',
        'Do you like writing by hand?',
        'Would you like to work with AI?',
        'Which film genres do you enjoy?',
        'Do you like watching trailers?',
        'Do you like looking at views?',
        'Which plant would you most like to grow?',
        'What do you like to do in natural places?',
        'Do you like the weather in your country?',
        'What kind of weather do you like the most?',
        'Do you like rainy days?',
        'Do you like cold weather?',
        'Do you enjoy winter festivals?',
        'Do you like watching sport on TV?',
        'Do you like travelling?',
        'What do you like about the countryside?',
        'Would you like to live somewhere like that in the future?',
        'Do you like your name?',
        'Do you like sugary food?',
        'What language would you like to learn next?',
        'Do you like trick mirrors in shops?',
        'Is there a collection you would like to start?',
        'Do you hate standing in a queue?',
        'Do you like your national flag?',
        'Do you enjoy learning new things?',
        'Would you like to read more than you do?',
        'Do you enjoy trying dishes from other countries?',
        'Do you enjoy choosing presents for people?',
        'Do you like the place where you live?',
        'Do you like your hometown more now than before?',
        'Do you like your job or studies?',
        'What do you like about your classmates or colleagues?',
        'Do you like spending time with your family?',
        'Do you like being around children?',
        'Do you like living with other people?',
        'Do you like your neighbourhood?',
        'Do you like eating out with friends?',
        'Do you like trying new food?',
        'Do you like spicy food?',
        'Do you like home-cooked meals?',
        'Do you like fruit and vegetables?',
        'Do you like buying food at markets?',
        'Do you like wearing casual clothes?',
        'Do you like following fashion trends?',
        'Do you like receiving surprise gifts?',
        'Do you like birthday cakes?',
        'Do you like fireworks?',
        'Do you like traditional festivals?',
        'Do you like the sound of music in shops?',
        'Do you like karaoke?',
        'Do you like live concerts?',
        'Do you like playing video games?',
        'Do you like watching sports on TV?',
        'Do you like going to the gym?',
        'Do you like swimming?',
        'Do you like hiking?',
        'Do you like spending time near water?',
        'Do you like looking at stars at night?',
        'Do you like watching the sunrise?',
        'Do you like taking care of plants?',
        'Do you like DIY projects?',
        'Do you like repairing things yourself?',
        'Do you like visiting historical places?',
        'Do you like going to parks?',
        'Do you like crowded places?',
        'Do you like quiet places?',
        'Do you like learning about other cultures?',
        'Do you like taking photos when you travel?',
        'Do you like sending postcards?',
        'Do you like drawing?',
        'Do you like your bedroom?',
    ]),
    ('Habits / Routines', [
        'How long do you spend on your studies each week?',
        'How often does the whole family get together?',
        'What do you usually do with your family at the weekend?',
        'What time do you usually get up during the week?',
        'Is your routine different at the weekend?',
        'Do you ever follow exactly the same routine every day?',
        'What do you usually do first thing in the morning?',
        'Has your morning routine changed in the last few years?',
        'Do you usually go to bed at the same time every night?',
        'What do you usually do on your day off?',
        'Do you ever spend your whole day off at home?',
        'What do you do with an hour of unexpected free time?',
        'How much time do you give to your hobbies?',
        'Where do people usually see wild animals in your country?',
        'Do you ever watch birds?',
        'What do you usually eat for breakfast?',
        'Do you ever go shopping just for pleasure?',
        'Do you often buy things online?',
        'Are online prices always better than shop prices?',
        'What do you usually wear during the week?',
        'Do you usually manage to save money?',
        'How do you decide what to give somebody?',
        'How do you usually celebrate your birthday?',
        'How do you feel about singing in public?',
        'Do you ever go to art exhibitions?',
        'How often do you visit museums?',
        'How often do you look back at old photos?',
        'Where do you usually read?',
        'Do you ever send letters by post?',
        'Do you check the news every day?',
        'How do you usually get your news?',
        'How often do you reach for your phone?',
        'How much time do you spend on social media?',
        'Do people post too much of their daily life online?',
        'How often do you use a computer?',
        'What kind of programmes do you usually watch?',
        'How often do you go to the cinema?',
        'How do you feel when it starts to rain suddenly?',
        'Where does it usually rain in your country?',
        'What do you do on a rainy weekend?',
        'How do you dress differently in winter and summer?',
        'Do you exercise regularly?',
        'How do you stay motivated to keep fit?',
        'Do you ever commute by bicycle?',
        'Do you often use public transport?',
        'How do you prepare before a trip?',
        'Where do you usually go for holidays?',
        'Do you plan every day of your holiday?',
        'What do you do at the beach?',
        'Are you usually good at numbers?',
        'How do you greet people in your country?',
        'How many days a week do you stay home?',
        'What usually motivates you?',
        'What do you do to look after your health?',
        'How often do you have your hair cut?',
        'What do you do with used bottles?',
        'How much time do you spend on vocabulary each day?',
        'How often do you take a nap?',
        'How often do you check your hair in a mirror?',
        'What do you do while you wait in a line?',
        'Who do you usually ask for help?',
        'Are you usually on time?',
        'What do you write every day?',
        'Do you often call your friends?',
        'Do you usually make plans for the weekend?',
        'When do you usually find time to read?',
        'Is your daily routine the same every day?',
        'How often do you look at your phone each day?',
        'How often do you eat out?',
        'How often do you visit your parents?',
        'How often do you travel?',
        'How often do you go to the market?',
        'How often do you exercise?',
        'How often do you watch the news?',
        'How often do you use social media?',
        'How often do you clean your room?',
        'How often do you tidy your desk?',
        'How often do you make your bed?',
        'How often do you take public transport?',
        'How often do you eat breakfast at home?',
        'How often do you eat with your family?',
        'How often do you buy clothes?',
        'How often do you give gifts?',
        'How often do you celebrate with friends?',
        'How often do you check your messages?',
        'How often do you back up your files?',
        'How often do you read for pleasure?',
        'How often do you watch films?',
        'How often do you listen to music while studying?',
        'How often do you go for walks?',
        'How often do you go to bed late?',
        'How often do you dream?',
        'How often do you spend time outdoors?',
        'How often do you eat fruits and vegetables?',
        'How often do you drink water during the day?',
        'How often do you take a break when studying?',
        'How often do you chat with your neighbours?',
        'How often do you help with housework?',
        'How often do you plan your week?',
        'How often do you buy things you do not need?',
    ]),
    ('Past Experiences', [
        'What did you want to be when you were a child?',
        'Have you ever thought about changing your job or course?',
        'How did you meet your closest friend?',
        'What did you use to do in the mornings when you were a child?',
        'Were your weekends different when you were a child?',
        'Were your hobbies as a child different from your hobbies now?',
        'What did you love doing most as a child?',
        'Which childhood activities do you still do now?',
        'Did you have a favourite toy when you were little?',
        'Is there something from your childhood you would like to try again?',
        'Did you ever have a pet when you were a child?',
        'Have you ever helped a stray animal?',
        'Did you learn to cook from somebody?',
        'Have you ever cooked a meal for guests?',
        'Did you eat a lot of sweets when you were young?',
        'Has the way you shop changed recently?',
        'What did you last buy online?',
        'What did you wear when you were at school?',
        'Have you ever been given a gift you did not like?',
        'Did you enjoy birthday parties as a child?',
        'Have the way people celebrate changed recently?',
        'Did you ever learn to play an instrument?',
        'What music were you listening to when you were younger?',
        'When was the last time you danced?',
        'Did you draw as a child?',
        'Do photos help you remember things?',
        'Have you ever read the same book twice?',
        'Have you ever kept letters or postcards?',
        'When did you last write a long email?',
        'Did you have a phone as a teenager?',
        'Have you ever paid for an app?',
        'Did you watch more TV as a child?',
        'Have you ever been on a very long walk?',
        'Have you ever spent the night in nature?',
        'Have you ever been in a school team?',
        'What sport did you prefer at school?',
        'Did you learn to swim as a child?',
        'Have you ever travelled alone?',
        'Have you lived in the countryside?',
        'Have you ever climbed a mountain?',
        'Do you remember most of your dreams?',
        'Have you ever acted on something from a dream?',
        'Do you have a good memory?',
        'Have you ever changed your hair style completely?',
        'How do you remember new English words?',
        'Have you ever become friends with a stranger?',
        'Do you always remember your keys?',
        'Have you ever been locked out?',
        'Did you collect things as a child?',
        'Have you ever forgotten something without a reminder?',
        'Did you like doing arts and crafts as a child?',
        'Did you keep a diary as a teenager?',
        'When did you last help a stranger?',
        'Is it easier to learn as a child?',
        'Have you ever had a weekend trip?',
        'Did you like your primary school?',
        'What was your favourite subject at school?',
        'Did you have a best friend at school?',
        'Did you walk to school when you were young?',
        'Did you go to school by bus or by bicycle?',
        'Did you eat lunch at school or at home?',
        'Did you do homework in the evening?',
        'Did you join any clubs at school?',
        'Did you play any musical instrument as a child?',
        'Did you learn a foreign language at school?',
        'Did you take part in school performances?',
        'Did you celebrate your birthdays as a child?',
        'Did you wear a uniform at school?',
        'Did you have a favourite teacher?',
        'Did you ever skip a meal when you were young?',
        'Did you watch cartoons when you were little?',
        'Did you read fairy tales as a child?',
        'Did you collect anything when you were young?',
        'Did you play with toys when you were a child?',
        'Did you go camping as a child?',
        'Did you visit your grandparents often?',
        'Did you have dinner with your family as a child?',
        'Did you help your parents at home when you were young?',
        'Did you ever get lost when you were young?',
        'Did you learn to ride a bicycle as a child?',
        'Did you swim in the sea as a child?',
        'Did you eat street food when you were young?',
        'Did you have a pet growing up?',
        'Did you travel abroad as a child?',
        'Did you visit museums on school trips?',
        'Did you enjoy sports at school?',
        'Did you ever compete in a race?',
        'Did you make friends easily at school?',
        'Did you move house as a child?',
        'Did you change schools when you were young?',
        'Did you receive pocket money as a child?',
        'Did you save money when you were young?',
        'Did you use a phone as a teenager?',
        'Did you watch the same film more than once as a child?',
        'Did you learn to cook when you were young?',
        'Did you plant anything when you were a child?',
        'Did you take care of a younger sibling?',
        'Did you ever go to a summer camp?',
        'When did you last make a gift or a card for someone?',
        'Did you sing in a choir at school?',
    ]),
    ('Reasons / Explanations', [
        'Why do some people still prefer paper news?',
        'Why are international series so popular?',
        'Why do fans feel so loyal to one team?',
        'Why do so many people give up exercise?',
        'Why are cycle lanes becoming popular?',
        'Why do city people keep visiting villages?',
        'Why do some people love mountain trips?',
        'Why do some young people in your country eat badly?',
        'Why are you learning English?',
        'Why do some adults collect objects?',
        'Why do queues form so often in your city?',
        'Why do some people always run late?',
        'Why do some families skip breakfast?',
        'Why did you choose your current job or course?',
        'Why did you choose to live where you live now?',
        'Why do you like your hometown?',
        'Why do you enjoy spending time with your family?',
        'Why is your home important to you?',
        'Why do you like your current job or studies?',
        'Why do you like cooking?',
        'Why do you prefer to eat at home?',
        'Why do you like a certain type of music?',
        'Why do you enjoy reading?',
        'Why did you start learning English?',
        'Why do you think you learn English well?',
        'Why do you like travelling?',
        'Why do you like taking photos?',
        'Why do you enjoy your hobby?',
        'Why did you choose this hobby?',
        'Why do you like shopping?',
        'Why do you prefer shopping online?',
        'Why do you like a certain sport?',
        'Why did you choose that sport?',
        'Why do you like watching films?',
        'Why do you prefer watching films at home?',
        'Why do you like your city?',
        'Why do you prefer the countryside?',
        'Why do you like the weather in your area?',
        'Why did you choose to study your subject?',
        'Why do you like your job?',
        'Why do you prefer mornings?',
        'Why do you like quiet places?',
        'Why do you prefer crowded places?',
        'Why do you like making friends?',
        'Why do you prefer a few close friends?',
        'Why do you like keeping pets?',
        'Why did you choose your phone?',
        'Why do you like using social media?',
        'Why do you avoid social media?',
        'Why do you like walking?',
        'Why do you prefer cycling?',
        'Why do you like taking the bus?',
        'Why do you prefer driving?',
        'Why do you like your neighbourhood?',
        'Why do you enjoy festivals?',
        'Why do you like traditional food?',
        'Why do you like trying new food?',
        'Why do you prefer reading paper books?',
        'Why do you prefer e-books?',
        'Why do you like writing by hand?',
        'Why do you prefer typing?',
        'Why do you like listening to music?',
        'Why do you enjoy podcasts?',
        'Why do you like watching the news?',
        'Why do you avoid the news?',
        'Why do you like waking up early?',
        'Why do you prefer sleeping in?',
        "Why do you like your hometown's food?",
        'Why do you enjoy cooking for guests?',
        'Why do you like giving gifts?',
        'Why do you enjoy receiving presents?',
        'Why do you like your name?',
        'Why did your parents choose that name?',
        'Why do you like taking the window seat?',
        'Why do you prefer travelling by train?',
        'Why do you like window shopping?',
        'Why do you prefer buying quickly?',
        'Why do you like bright colours?',
        'Why do you prefer dark colours?',
        'Why do you like short hair?',
        'Why do you prefer long hair?',
        'Why do you like meeting new people?',
        'Why do you prefer staying with old friends?',
        'Why do you like indoor hobbies?',
        'Why do you prefer outdoor activities?',
        'Why do you like a packed schedule?',
        'Why do you prefer a free schedule?',
        'Why do you like planning things?',
        'Why do you prefer doing things spontaneously?',
        'Why do you like walking to work or college?',
        'Why do you prefer the subway?',
        'Why do you like watching sport?',
        'Why do you prefer playing sport?',
        'Why do you like studying with others?',
        'Why do you prefer studying alone?',
        'Why do you like taking notes by hand?',
        'Why do you prefer taking notes on a laptop?',
        'Why do you like making lists?',
        'Why do you prefer remembering things without notes?',
        'What is the reason you get up at the same time every day?',
    ]),
    ('Opinions about Familiar Topics', [
        'Do you think mornings are the most productive time of the day?',
        'Do you find it easy to fall asleep?',
        'What is the best way to spend a weekend?',
        'Do you think you have enough free time?',
        'What kind of pets are popular in your country?',
        'Should families with small children keep pets?',
        'Which birds are common near your home?',
        'Is breakfast the most important meal of the day in your opinion?',
        'Is street food popular in your country?',
        'Should sugary food be taxed?',
        'Do you think people eat healthy snacks?',
        'Should traditional clothing be worn more often?',
        'What is the best gift you have ever received?',
        'What is the most common gift to give at visiting?',
        'Should there be more public holidays?',
        'Which festivals are the most popular in your country?',
        'Should children be encouraged to sing?',
        'Should children learn to dance at school?',
        'Should art lessons be part of the school timetable?',
        'Should museums be free for students?',
        "Should some things stay private even on friends' feeds?",
        'Should parents limit the number of hours of games?',
        'Do you think television will disappear one day?',
        'Should cities save old buildings?',
        'Should every district have a park?',
        'Should offices have plants?',
        'Is it important for children to spend time in nature?',
        'Should swimming be taught in schools?',
        'Should beaches be open to everyone?',
        'Even artists can feel shy. Do you agree?',
        'Do you think more people will stay at home to work?',
        'Do you think you live a healthy life?',
        'Should people eat less sugar?',
        'Should not recycling be a fine?',
        'What is the best age to learn a language?',
        'Do you find it easy to ask for help?',
        'Should shops show the national flag more often?',
        'Should young people own a car automatically?',
        'Should adults go to class?',
        'Should children help with cooking?',
        'Do you think your city is a good place to live?',
        'Do you think young people have enough free time?',
        'Do you think homework is necessary?',
        'Do you think breakfast is important?',
        'Do you think fast food is bad for health?',
        'Do you think walking is enough exercise?',
        'Do you think pets are good for children?',
        'Do you think fashion is important?',
        'Do you think people spend too much on clothes?',
        'Do you think saving money is important for young people?',
        'Do you think gifts should be expensive?',
        'Do you think surprise gifts are better than planned ones?',
        'Do you think festivals are important for a country?',
        'Do you think music can change your mood?',
        'Do you think everyone should learn to swim?',
        'Do you think it is good to live alone?',
        'Do you think it is better to live with family?',
        'Do you think city life is healthier than village life?',
        'Do you think people should exercise every day?',
        'Do you think shopping online is better than in stores?',
        'Do you think young people should learn to cook?',
        'Do you think parks are important in cities?',
        'Do you think people read enough nowadays?',
        'Do you think handwriting will disappear?',
        'Do you think public transport is good value for money?',
        'Do you think children should get pocket money?',
        'Do you think birthdays matter more as you grow older?',
        'Do you think people take too many photos?',
        'Do you think people sleep enough?',
        'Do you think people should buy fewer things?',
        'Do you think schools should teach money skills?',
        'Do you think everyone should learn a second language?',
        'Do you think online friends are real friends?',
        'Do you think people cook less than before?',
        'Do you think markets are better than supermarkets?',
        'Do you think people should spend more time outside?',
        'Do you think recycling should be easier for people?',
        'Do you think it is good to have a daily routine?',
        'Do you think young people should help at home?',
        'Do you think living in a small town is boring?',
        'Do you think holidays are the best part of the year?',
        'Do you think people should visit their families more often?',
        'Do you think cafes are good places to study?',
        'Do you think people should cook with their children?',
        'Do you think art classes are useful for everyone?',
        'Do you think sport should be optional at school?',
        'Do you think people should listen to music every day?',
        'Do you think news on social media is trustworthy?',
        'Do you think it is important to keep a work-life balance?',
        'Do you think people should use cash at markets?',
        'Do you think friends should live close to each other?',
        'Do you think it matters whether your home is big or small?',
        'Do you think people dress better for formal occasions?',
        'Do you think celebrating small wins is healthy?',
        'Do you think taking breaks is part of studying?',
        'Do you think hobbies should be shared with family?',
        'Do you think every student should have a part-time job?',
        'Do you think people should learn basic first aid?',
        'Do you think living with housemates teaches teamwork?',
        'Do you think people keep things longer than they should?',
    ]),
]

# ====================================================================
# PART 2 - 6 cue-card categories x 25 cards; each card gets 4 bullet variants.
# ====================================================================
_P2_CARDS = {
    'person': ['a person you admire', 'an older person you know well', 'a friend you have known for a long time', 'a person who helped you when you needed it', 'a person who speaks a foreign language very well', 'a famous person you would like to meet', 'a teacher who influenced you', 'a person with an interesting or unusual job', 'a family member who means a lot to you', 'a person who makes you laugh', 'a cheerful person you know', 'a person who never gives up easily', 'a person you would like to work with', 'a person who lives in another country and whom you admire', 'a person who taught you an important lesson', 'a person who is always on time', 'a person you first met at a party', 'a person who gives good advice', 'a person who looks after their health carefully', 'a person who does not talk very much', 'a person you are proud to know', 'a person who loves trying new things', 'a person who always makes you laugh', 'a person you know who is good at saving money', 'a person you spend time with at weekends'],
    'place': ['a beautiful city you have visited', 'a place you discovered by chance', 'a quiet place you like to escape to', 'a city you would like to work in one day', 'a place you often go to in your free time', 'a holiday place you remember well', 'a place you would like to visit for a short break', 'a house or apartment you have lived in', 'a room in your home that you like the most', 'a park in your city', 'a famous street in your country', 'an old building you like', 'a modern building that impresses you', 'a library where you used to study', 'a market you have visited', 'a café you enjoy sitting in', 'a place near your home that is full of history', 'a green space in the middle of a busy city', 'a place in nature with wonderful scenery', 'a place that is always crowded when you go', 'a quiet corner of your hometown', 'a place you visited that was surprisingly clean', 'a place full of history in your country', 'a place where you can be alone with your thoughts', 'a place you visit whenever you need to calm down'],
    'object': ['a useful app on your phone', 'a book you have enjoyed reading', 'something you bought that made you happy', 'something expensive you would love to buy', 'a piece of jewellery you own', 'a device you cannot leave home without', 'a favourite piece of clothing in your wardrobe', 'the traditional drink of your country', 'a dish people always ask you to cook', 'a photograph that means a lot to you', 'an invention that changed the way you live', 'something you bought that you regret', 'an object you keep that has a story', 'a toy you loved as a child', 'a special meal you know how to cook', 'a map that you like', 'a pen you really like', 'a piece of furniture in your home', 'a book you read more than once', 'a machine in your home you use daily', 'an object from your childhood that you still keep', 'a cheap thing that turned out to be great', 'a thing that helps you stay organised', 'a thing you take with you everywhere', 'a thing that reminds you of your hometown'],
    'event': ['a time you were really happy', 'a time someone helped you', 'a time you helped a stranger', 'a time you had a long conversation with an older person', 'a time you changed your opinion about something', 'a time you learnt a valuable lesson', 'a time you were proud of something you did', 'a time you made a mistake and fixed it', 'a time you taught somebody something new', 'a time you had to make an important decision', 'a time you got lost', 'a time you visited a place for the first time', 'a time you had an unexpected visitor', 'a time the weather completely changed your plans', 'a time you had to do something you did not want to do', 'a time you saw somebody you admire succeed', 'a time you had to wait for a very long time', 'a time you worked for many hours', 'a time you had to stand in a long queue', 'a time you spent the evening with your family', 'a time you enjoyed a big family meal', 'a time you laughed more than usual', 'a time you fixed something at home', 'a time you gave somebody useful advice', 'a time you tried something completely new'],
    'activity': ['an activity you do to keep fit', 'an activity you enjoy during public holidays', 'an activity you do with your family', 'an activity you do when you are stressed', 'an activity you took up recently', 'an activity you do in the evening', 'an activity you always do at the weekend', 'an activity that helps you concentrate', 'an activity you do with friends', 'an activity you did with your classmates', 'an activity you would like to do more often', 'an activity you enjoy in the summer', 'an activity you do with children', 'an activity you do alone', 'an activity you enjoy doing on a rainy day', 'an activity you enjoy doing outdoors', 'an activity that is popular in your country', 'an activity you would like to teach others', 'an activity you do early in the morning', 'an activity you do to relax after work', 'an activity you did last weekend', 'an activity you enjoy doing in a group', 'an activity you would like to learn', 'an activity you do when friends come', 'an activity you enjoy doing at home'],
    'future': ['a future plan you have for your studies', 'a place you would like to visit one day', 'a job you would like to do in the future', 'a skill you would like to learn in the future', 'a city you would like to live in one day', 'a country you would like to travel to later', 'a habit you would like to build', 'a hobby you would like to take up', 'a goal you have for the next year', 'a change you would like to make to your home', 'a person you would like to collaborate with', 'a trip you are planning for the future', 'an event you are looking forward to in the future', 'a car you would like to buy one day', 'a house you would like to own in the future', 'a festival celebration you would like to attend', 'a language you would like to master', 'a meal you would like to learn to cook', 'a sport you would like to try in the future', 'a pet you would like to keep one day', 'a project you would like to start', 'a country you would like to work in someday', 'a job you would like to change to in five years', 'a goal you would like to achieve before you are 30', 'a tradition you would like to remember and keep'],
}

_P2_BULLETS = {
    'person': [('who this person is', 'how you know them', 'what they are like', 'explain why you admire or enjoy being around this person'), ('who this person is', 'when you first met them', 'how often you spend time together', 'explain what they bring to your relationship'), ('who this person is', 'what you know about their life', 'what you usually talk about', 'explain why this person is important to you'), ('who this person is', 'how long you have known them', 'what they have taught you', 'explain what you would do without their advice')],
    'place': [('where it is', 'how you first found out about it', 'whom you go there with', 'explain why you like the place so much'), ('where it is', 'what you notice when you arrive', 'what you remember about your first visit', 'explain what you usually do in or around it'), ('where the place is', 'what you like doing there', 'how you often find yourself there', 'explain why it stays in your memory'), ('where the place is', 'when you last visited it', 'what the best part of the visit was', 'explain whether you plan to go back soon')],
    'object': [('what it is', 'where and when you first got it', 'how you use it', 'explain why it is important to you'), ('what it is', 'what it looks and feels like', 'where you keep it', 'explain why you chose that particular one'), ('how you came to own it', 'what you do with it', 'how long you have had it', 'explain how it makes your life easier'), ('what it is', 'the story behind it', 'who it reminds you of', 'explain why you would never get rid of it')],
    'event': [('what the situation was', 'when and where it happened', 'who was involved', 'explain how you felt about it at the time'), ('what the situation was', 'why it happened', 'what you did', 'explain what the experience taught you'), ('what the situation was', 'who you were with', 'how long it lasted', 'explain what happened afterwards'), ('what the situation was', 'why you remember it so clearly', 'how you reacted', 'explain how it changed your plans')],
    'activity': [('what the activity is', 'how often you do it', 'who you do it with', 'explain why you enjoy it'), ('what the activity is', 'where you usually do it', 'how long it takes', 'explain what it gives you'), ('what the activity is', 'when you started it', 'what you need for it', 'explain how it makes you feel'), ('what the activity is', 'where you first did it', 'what you like about it', 'explain how it helps you')],
    'future': [('what the plan or situation is', 'when you would like it to happen', 'how you would prepare', 'explain how you would feel'), ('what the plan or situation is', 'why you chose it', 'what steps you would take first', 'explain what it would change'), ('what the plan or situation is', 'who would be involved', 'where it would take place', 'explain what makes it special'), ('what the plan or situation is', 'how long it would last', 'what you would need', 'explain what you would do after')],
}

# ====================================================================
# PART 3 - 8 categories x 100. Question numbering restarts at 1 in Part 3.
# ====================================================================
_P3 = [
    ('Opinion', [
        'Is a university degree still worth the money?',
        'Should schools focus more on creativity or on preparing students for exams?',
        'What role should technology play in education?',
        'Should school uniforms be compulsory?',
        'Do children need homework at all?',
        'Do exams really show what students can do?',
        'Should students be allowed to take an exam again without a low score?',
        'Should young people go to university or start working after school?',
        'Should universities be free for everyone?',
        'Should children start a second language very early?',
        'What is the best way to learn a language outside a classroom?',
        'Are native speakers expected to study other languages?',
        'Do children today spend too much time on screens?',
        'Should parents set limits on screen time?',
        'How has technology changed the way children play?',
        'Is social media a positive or a negative force for young people?',
        'Should governments control social media companies?',
        'Are we happy about how much time we spend online?',
        'Can privacy really exist on the internet today?',
        'Should companies be allowed to collect our data?',
        'Do you trust apps with your personal information?',
        'Are home workers more productive?',
        'Should students study for one career for life?',
        'Are most young people satisfied with their jobs?',
        'Should salary be the first thing people consider at work?',
        'Should the state pay people who cannot find a job?',
        'Do young people save enough money?',
        'Should money skills be taught in school?',
        'Is our society too interested in buying things?',
        'Are people happier when they own more objects?',
        'Should adverts be banned in schools?',
        'Has online shopping made people buy things they do not need?',
        'How do adverts persuade people to buy?',
        'Is advertising on children fair?',
        'Should unhealthy food adverts be banned?',
        'Do you trust the claims you see in adverts?',
        'Should individuals do more to save the environment?',
        'Who should pay for fighting climate change, governments or families?',
        'Should recycling be the law?',
        'Should plastic packaging be taxed?',
        'What could make traffic pollute less, fast?',
        'Are local authorities responsible for the air you breathe?',
        'Should cities plant more trees along the roads?',
        'Can parks in every neighbourhood change a city?',
        'Is sustainable living on the rise in your country?',
        'Can renewable energy replace coal and oil?',
        'Should homeowners get help to install solar panels?',
        'Should buses and trains be free in big cities?',
        'Should cities build more underground railways?',
        'Are rents too high in your country?',
        'Should the government build cheap housing?',
        'Should governments build cheaper homes?',
        'Is renting always money thrown away?',
        'Do people care how their home looks to others?',
        'What can cities learn from villages?',
        "Does tourism help your country's economy?",
        'Should famous heritage sites be closed sometimes?',
        'Are traditional celebrations disappearing?',
        'How do young people feel about their traditions?',
        'Should families keep the old customs?',
        'Can celebrations be modernised without losing themselves?',
        'Should grandparents live with their grandchildren?',
        'Can online friends be real friends?',
        'How do old friends stay in touch?',
        'Are children over-scheduled with after-school clubs?',
        'Should children simply be free to play?',
        'How much freedom should a child get?',
        'Should the young be we supposed to be optimistic?',
        'Should young people travel before they settle down?',
        'Who should care for elderly people?',
        'Do pensioners receive enough money in your country?',
        'Should some gyms be free?',
        'Do people in your country talk about mental health enough?',
        'Who should decide what children eat, parents or the state?',
        "Can school canteens change children's diets?",
        'Is healthy food always expensive?',
        "Is there too much competition in children's sport?",
        'Do famous athletes deserve their huge salaries?',
        'Is watching TV a waste of time?',
        'Do streaming platforms make us lazy?',
        'How has cinema changed in the last twenty years?',
        'Should every child learn music at school?',
        'Are local musicians losing out to international artists?',
        'Is the reading habit dying in a video-first world?',
        'Should great books be part of every syllabus?',
        'Can people really trust the news today?',
        'Should journalists write anything they like?',
        'How has social media changed the way we understand news?',
        'Should museums be free?',
        'How do museums stay interesting for young visitors?',
        'Who should take care of old buildings?',
        'What digital technologies help museums teach?',
        'Does tourism help nations understand each other?',
        'Should students take a travel gap before university?',
        'Is space travel just a very expensive game?',
        'What could a space programme teach ordinary people?',
        'Should we plan to live on Mars?',
        'How much should a country spend on satellites?',
        'Is science taught in a boring way?',
        'Should science decide the rules of our lives?',
    ]),
    ('Comparison', [
        'How do schools in cities differ from schools in small villages?',
        'Do children learn better in small classes?',
        'Are prices rising faster than salaries?',
        'Is it better to live in a house or in a flat in town?',
        'Do people in the countryside live better lives?',
        'Are modern families less close than older ones?',
        'Is it easier to make friends today than in the past?',
        'Is a good friend more valuable than a good salary?',
        'Are young people more stressed than their parents were?',
        'Is it better for old people to live in homes?',
        'Is it true that health is more valuable than money?',
        'Which matters more in the news, speed or accuracy?',
        'Is it better to travel alone or in a group?',
        'Are effort more important than talent?',
        'Is donating money better than donating time?',
        'Are needs different from wants today?',
        'Do you embrace technology faster than your grandparents do?',
        'Are modern homes less demanding than before?',
        'Is it better to charge more for quality?',
        'Do people fear public speaking more than flying?',
        'Is teamwork always better than working alone?',
        'Is global culture making countries similar?',
        'Do old cities inspire more than new?',
        'Do people sleep less today than in the past?',
        'Are people more stressed today than they were in the past?',
        'What can audio formats teach us that books cannot?',
        'Is handmade quality better than machine quality?',
        'Are card payments safer than cash?',
        'Do small shops still have any advantages over big supermarkets?',
        'Do people enjoy surprises or do they prefer plans?',
        'Do local elections matter more than national ones?',
        'Do children learn faster than adults?',
        'Is every stage of life better than any other?',
        'What do people enjoy more, travelling to new places or staying at home?',
        'Is it better to plan a trip to the minute?',
        'Is eating out more popular now than it used to be?',
        'Is home food healthier than eating out?',
        'Is learning at school better than learning online?',
        'Are lessons with a teacher more effective than self-study?',
        'Is city life more stressful than country life?',
        'Is living in a flat better than living in a house?',
        'Is shopping in a mall more convenient than online shopping?',
        'Are traditional markets more enjoyable than supermarkets?',
        'Is fast food worse than home-cooked meals?',
        'Is eating at home healthier than eating out?',
        'Is travelling by train more comfortable than by plane?',
        'Is a short holiday more refreshing than a long one?',
        'Is a big wedding better than a small one?',
        'Are birthday parties for children more exciting now than in the past?',
        "Is music from your youth better than today's music?",
        'Are live performances more special than recordings?',
        'Is watching a film at home better than at the cinema?',
        'Are TV series more popular than films nowadays?',
        'Are e-books more convenient than paper books?',
        'Is typing faster than writing by hand?',
        'Is texting more effective than calling?',
        'Are video calls better than voice calls?',
        'Is face-to-face communication more meaningful than online?',
        'Is a smartphone better than a laptop for students?',
        'Are laptops more useful than tablets?',
        'Is social media more entertaining than real conversation?',
        'Are video games more engaging than board games?',
        'Is playing sport better than watching it?',
        'Is walking better exercise than jogging?',
        'Is swimming easier than running?',
        'Is cycling more practical than driving in cities?',
        'Are trains more reliable than buses?',
        'Is driving a car more convenient than taking public transport?',
        'Are high-rise buildings better than traditional houses?',
        'Are old buildings more beautiful than modern ones?',
        'Is a garden better than a balcony?',
        'Are indoor plants better than fresh flowers?',
        'Is handmade work better than factory products?',
        'Are gifts that you make more meaningful than bought ones?',
        'Is spending money on experiences better than on things?',
        'Are souvenirs from markets better than those from shops?',
        'Is it better to save money or to enjoy it?',
        'Are cash payments safer than card payments?',
        'Is a fixed salary better than a flexible income?',
        'Are young employees more productive than older ones?',
        'Is working from home better than working in an office?',
        'Is a busy job more rewarding than a relaxed one?',
        'Are school uniforms better than casual clothes?',
        'Is studying abroad better than studying at home?',
        'Are private lessons more effective than school classes?',
        'Is homework more useful than revision in class?',
        'Are exams a fairer test than coursework?',
        'Is memorising more useful than understanding?',
        'Are small classes better than large ones?',
        'Is a gap year better than going straight to university?',
        'Are teachers more important than technology in class?',
        'Is reading more enjoyable than watching?',
        'Are documentaries more educational than films?',
        'Is the news on TV more reliable than news online?',
        'Are newspapers more trustworthy than social media?',
        'Is radio better than TV for news?',
        'Is it better to watch news or to read it?',
        'Are city parks more useful than playgrounds?',
        'Is keeping a pet more rewarding than growing plants?',
        'Are cats easier to keep than dogs?',
    ]),
    ('Reasons / Causes', [
        'Why do some people never use their degree at work?',
        'Why are so many companies offering remote work?',
        'Why do people change jobs so often?',
        'What makes a good manager?',
        'Why is unemployment higher among you if?',
        'Why do some countries recycle very little?',
        'What causes the most pollution in your city?',
        'What makes a city green?',
        'Why do people still choose cars over public transport?',
        'Why are people so attached to their own cars?',
        'Why do so many people want to live in cities?',
        'Why is housing hard for young people?',
        'Why do young people move away from villages?',
        'Why do parents and teenagers argue so much?',
        'Why do many young adults live with their parents longer?',
        'Why are so many people unhealthy today?',
        'Why is fast food so popular?',
        'Why are some countries so good at sport?',
        'Why does music seem to remember time so perfectly?',
        'Why do some readers still choose paper books?',
        'Why do so many people dream about travelling?',
        'Why do school students fear science?',
        'Why must ordinary citizens understand science?',
        'Why do rich people sometimes seem unhappy?',
        'What makes a city happy to live in?',
        'Why do some people believe in lucky days?',
        'Why do people commit crimes?',
        'Why do cities fight to host big sports events?',
        'What makes a family healthy and happy together?',
        'Why do some people keep it secret?',
        'Why is the news so full of bad news?',
        'Why are parks important in a city?',
        'Why do people still shop at small shops?',
        'Why is second-hand shopping becoming popular?',
        'Why do households waste so much food?',
        'Why has community spirit changed?',
        'Why do people enjoy trying new restaurants?',
        'Why is public speaking part of interviews?',
        'What makes a team work well?',
        'Why do people buy bottled water?',
        'Why do students stay up so late?',
        'Why do patients sometimes wait so long?',
        'Why do adults stop being active when they finish school?',
        'Why do families pay for private lessons?',
        'Why do many people still buy paper books?',
        'Why are interviews so nerve-wracking?',
        'What makes a neighbourhood feel safe?',
        'Why do some streets feel welcoming and others do not?',
        'Why do many people work as freelancers?',
        'Why are handmade products becoming popular again?',
        'What makes good service in a restaurant?',
        'Why do many pensions feel too low?',
        'Why do shops plan surprise promotions with such care?',
        'Why do some people find it hard to keep promises?',
        'What makes a promise between friends easier to keep?',
        'Why do young people need to know their history?',
        'Why are houseplants suddenly so popular?',
        "Why are some votes copied from a parent's opinion?",
        'Why is starting easy but stopping a habit hard?',
        'Why are modern families always busy?',
        'Why do people keep so many photos now?',
        'Why do some places complain about rain all year?',
        'Why are city centres always so crowded?',
        'Why do young people leave villages for cities?',
        'Why do people move to big cities?',
        'Why is housing so expensive in big cities?',
        'Why do people prefer living alone nowadays?',
        'Why do many families eat out more than before?',
        'Why has fast food become so popular?',
        'Why do people buy more than they need?',
        'Why do young people spend so much time online?',
        'Why do teenagers feel pressure about their appearance?',
        'Why are people so interested in celebrities?',
        'Why do people enjoy taking photos of food?',
        'Why are selfies so popular?',
        'Why do people share their lives on social media?',
        'Why do some people stop using social media?',
        'Why do people love travelling?',
        'Why do some people prefer staying at home?',
        'Why do people collect souvenirs?',
        'Why do people give gifts?',
        'Why do children get excited about festivals?',
        'Why do adults also enjoy festivals?',
        'Why do people celebrate birthdays every year?',
        'Why do some people avoid big celebrations?',
        'Why do people listen to sad music?',
        'Why do some songs become world-famous?',
        'Why do people play video games to relax?',
        'Why do people enjoy watching sport?',
        'Why do people get attached to their hometowns?',
        'Why do some people prefer the countryside?',
        'Why do people like walking in nature?',
        'Why do people take up gardening?',
        'Why do people keep pets?',
        'Why do some people fear animals?',
        'Why is breakfast often skipped?',
        'Why do people drink coffee every morning?',
        'Why has tea culture remained so strong?',
        'Why do people eat street food?',
        'Why do people cook less than before?',
    ]),
    ('Advantages / Disadvantages', [
        'What are the disadvantages of working at home?',
        'How can a city benefit passed the games?',
        'Do private tutors give some children an unfair advantage?',
        'Are holidays the best workplace benefit?',
        'Is a company car still a desirable benefit?',
        'What are the advantages of living in a big city?',
        'What are the disadvantages of city life?',
        'What are the benefits of living in the countryside?',
        'What are the drawbacks of village life?',
        'What are the advantages of living alone?',
        'What are the disadvantages of living alone?',
        'What are the benefits of living with a big family?',
        'What are the advantages of buying a home?',
        'What are the disadvantages of renting?',
        'What are the benefits of online shopping?',
        'What are the drawbacks of buying things online?',
        'What are the advantages of paying by card?',
        'What are the disadvantages of using cash?',
        'What are the benefits of cooking at home?',
        'What are the disadvantages of eating out often?',
        'What are the advantages of eating street food?',
        'What are the drawbacks of fast food?',
        'What are the benefits of doing sport?',
        'What are the disadvantages of competitive sport?',
        'What are the advantages of team sports?',
        'What are the drawbacks of exercising alone?',
        'What are the benefits of walking to work?',
        'What are the disadvantages of driving everywhere?',
        'What are the advantages of cycling?',
        'What are the drawbacks of cycling in bad weather?',
        'What are the benefits of public transport?',
        'What are the disadvantages of public transport?',
        'What are the advantages of travelling by train?',
        'What are the drawbacks of flying?',
        'What are the benefits of a gap year?',
        'What are the disadvantages of delaying university?',
        'What are the advantages of studying abroad?',
        'What are the drawbacks of studying abroad?',
        'What are the benefits of private lessons?',
        'What are the disadvantages of private tutoring?',
        'What are the advantages of homework?',
        'What are the drawbacks of too much homework?',
        'What are the benefits of school uniforms?',
        'What are the disadvantages of school uniforms?',
        'What are the advantages of boarding school?',
        'What are the drawbacks of boarding school?',
        'What are the benefits of learning music at school?',
        'What are the disadvantages of compulsory art classes?',
        'What are the advantages of taking exams?',
        'What are the drawbacks of exams?',
        'What are the benefits of working from home?',
        'What are the disadvantages of remote work?',
        'What are the advantages of a fixed schedule?',
        'What are the drawbacks of flexible hours?',
        'What are the benefits of a stable job?',
        'What are the disadvantages of a monotonous job?',
        'What are the advantages of being self-employed?',
        'What are the drawbacks of freelancing?',
        'What are the benefits of early retirement?',
        'What are the disadvantages of retiring too early?',
        'What are the advantages of keeping a pet?',
        'What are the drawbacks of owning a dog?',
        'What are the benefits of gardening?',
        'What are the disadvantages of growing your own food?',
        'What are the advantages of handmade gifts?',
        'What are the drawbacks of buying gifts online?',
        'What are the benefits of saving money?',
        'What are the disadvantages of saving too much?',
        'What are the advantages of spending on holidays?',
        'What are the drawbacks of spending without a plan?',
        'What are the benefits of learning a second language?',
        'What are the disadvantages of learning a language alone?',
        'What are the advantages of reading for pleasure?',
        'What are the drawbacks of reading only online?',
        'What are the benefits of watching documentaries?',
        'What are the disadvantages of watching too much TV?',
        'What are the advantages of video calls?',
        'What are the drawbacks of video calls?',
        'What are the benefits of taking photographs?',
        'What are the disadvantages of taking too many photos?',
        'What are the advantages of living in a small town?',
        'What are the drawbacks of living in a big city?',
        'What are the benefits of street markets?',
        'What are the disadvantages of supermarkets?',
        'What are the advantages of festivals for a community?',
        'What are the drawbacks of mass festivals?',
        'What are the benefits of morning exercise?',
        'What are the disadvantages of exercising at night?',
        'What are the advantages of swimming?',
        'What are the drawbacks of swimming in the sea?',
        'What are the benefits of hiking?',
        'What are the disadvantages of extreme sports?',
        'What are the advantages of keeping a diary?',
        'What are the drawbacks of sharing everything online?',
        'What are the benefits of a daily routine?',
        'What are the disadvantages of a rigid routine?',
        'What are the advantages of learning from mistakes?',
        'What are the drawbacks of always being corrected?',
        'What are the benefits of travelling alone?',
        'What are the disadvantages of travelling in a group?',
    ]),
    ('Hypothetical', [
        'What would you do if you were the mayor of your city for a year?',
        'If you could change one rule in your school, which one would you choose?',
        'How would your life change if there were no internet for six months?',
        'Would you accept a well-paid job that left you no free time?',
        'If you could live in any country for a year, where would you go and why?',
        'What would happen in your city if private cars were banned?',
        'If you could invent one machine to help older people, what would it be?',
        'Would you still be happy if you could never use social media again?',
        'If you had to give up one modern device forever, which one would you choose?',
        'How would schools be different if you were the education minister?',
        'What would you do if you suddenly received a large sum of money?',
        'If you could design a house from scratch, what would you include?',
        'Would you rather live in a small village or a huge city in the future?',
        'If children grew up with no homework at all, would they learn less?',
        'What would happen if people stopped reading printed books completely?',
        'If you could spend one day shadowing any professional, who would you follow?',
        'Would you want to live on a spacecraft one day if it were safe?',
        'If you were a shop owner, what kind of shop would you open?',
        'What would you change at work if you were the boss for a week?',
        'If the planet ran out of water, how would everyday life change?',
        'Would you have kept doing your childhood hobby if you could?',
        'If you had to give a speech to your whole city, what would you talk about?',
        'What would you do if a whole month of public holidays was announced tomorrow?',
        'If you could travel back in time, which era would you visit?',
        'What would you do if a close friend borrowed money and never returned it?',
        'Would you move abroad if a job offer came, even with no friends there?',
        'If you were the owner of a small hotel, what would make guests return?',
        'How would you spend a week if all your devices were taken away?',
        'Would you buy a used phone?',
        'If you could live in any city, which one would you choose?',
        'If you had a free year, how would you spend it?',
        'If you won a large sum of money, what would you do first?',
        'If you could change one law, what would you change?',
        'If you were the mayor, what would you improve in your city?',
        'If you could meet any historical figure, who would you choose?',
        'If you could have any job for one day, what would it be?',
        'If you could invent something, what would you invent?',
        'If you could speak any language perfectly, which one would you choose?',
        'If you could live in another country for a year, where would you go?',
        'If you could design a house, what would it look like?',
        'If you could remove one stressful thing from life, what would it be?',
        'If you were a teacher, how would you teach differently?',
        'If you could change your school years, what would you change?',
        'If you had no phone for a month, how would you manage?',
        'If the internet disappeared for a week, what would you do?',
        'If you could give every child one skill, what would it be?',
        'If you could eat only one cuisine for life, which would it be?',
        'If you could time travel, would you go to the past or the future?',
        'If you could live to 150, would you want to?',
        'If you could have any pet, what would you choose?',
        'If you could ban one thing in society, what would it be?',
        'If you were a shop owner, what would you sell?',
        'If you could restart your career, what would you do?',
        'If you could study any subject, what would you learn?',
        'If you could be famous, what would you want to be known for?',
        'If you could make one city rule, what would it be?',
        'If you had to move abroad tomorrow, what would you miss most?',
        'If you could choose your working hours, what would they be?',
        'If you could live anywhere in nature, where would you go?',
        'If you could bring back one tradition, what would it be?',
        'If you could be any age again, which age would you choose?',
        'If you could give your younger self one advice, what would it be?',
        'If you could swap lives with someone for a day, who would it be?',
        'If you could write a book, what would it be about?',
        'If you could make a film, what story would you tell?',
        'If you could have dinner with anyone, who would you invite?',
        'If you could learn any musical instrument, which one would you pick?',
        'If you could visit any planet, would you go?',
        'If you could freeze time, what would you do?',
        'If you could relive one day, which day would you choose?',
        'If you could change your name, would you?',
        'If you could add one day to the week, what would you do with it?',
        'If you could erase one technology, what would it be?',
        'If you could give everyone one habit, what would it be?',
        'If you could decide school subjects, which would you keep?',
        'If you could choose a uniform for everyone, what would it be?',
        'If you could live under the sea, would you?',
        'If you could have a robot, what would it do?',
        'If you could communicate with animals, what would you ask?',
        'If you could change the weather, what would you change?',
        'If you could grow any food at home, what would you grow?',
        'If you could make one meal for the world, what would it be?',
        'If you could own a shop, what kind would you open?',
        'If you could preserve one old building, which would you save?',
        'If you could redesign your street, what would you change?',
        'If you could pick a new hobby, what would you start?',
        'If you could exercise less but stay fit, would you?',
        'If you could watch any live event, which would you choose?',
        'If you could record one memory, which would it be?',
        'If you could send one message to the world, what would you say?',
        'If you could be any animal, what would you be?',
        'If you could live without sleep, would you?',
        'If you could remember everything, would you want to?',
        'If you could eat dessert instead of meals, would you?',
        'If you could travel for free, where would you go first?',
        "If you could choose your children's hobbies, would you?",
        'If you could remove noise from cities, what would that change?',
        'If you could make school free for everyone, would you?',
        'If you could give every student a tablet, would that help?',
        'If you could make one thing healthier, what would it be?',
    ]),
    ('Prediction / Future', [
        'How will education change in the next ten years?',
        'Can people become addicted to social media?',
        'And will office buildings disappear in the future?',
        'How will automation change jobs in the next twenty years?',
        'Which jobs will remain safe from machines?',
        'What new careers will appear in the future?',
        'How do you think online series will change the way people watch in the future?',
        'Will artificial intelligence do more good than harm?',
        'Will AI remove more jobs than it creates?',
        'What happens when a country becomes older?',
        'What will life be like in fifty years?',
        'How can a street become friendlier?',
        'Should libraries become community centres?',
        'Will audio books and podcasts become even more popular in the future?',
        'Will every job in the future be a gig?',
        'Will people still read books in fifty years?',
        'Will paper books disappear?',
        'Will people stop writing by hand?',
        'Will shopping malls disappear?',
        'Will online shopping replace shops completely?',
        'Will cash disappear?',
        'Will cars be replaced by electric ones?',
        'Will driverless cars become common?',
        'Will people travel less in the future?',
        'Will work from home become permanent?',
        'Will offices disappear?',
        'Will robots take over most jobs?',
        'Will artificial intelligence replace teachers?',
        'Will children study mainly online in the future?',
        'Will schools still exist in the future?',
        'Will exams be replaced by other assessments?',
        'Will universities lose their value?',
        'Will languages die out?',
        'Will English become the only world language?',
        'Will people eat more lab-grown food?',
        'Will fast food become healthier?',
        'Will people cook less in the future?',
        'Will restaurants change?',
        'Will people exercise more or less in the future?',
        'Will cities become more crowded?',
        'Will people move back to the countryside?',
        'Will houses become smarter?',
        'Will people live longer?',
        'Will the population age?',
        'Will families become smaller?',
        'Will people marry later?',
        'Will people have fewer children?',
        'Will social media survive the next twenty years?',
        'Will people talk less face to face?',
        'Will video calls replace meetings?',
        'Will television disappear?',
        'Will radio disappear?',
        'Will newspapers survive?',
        'Will people watch films at home instead of cinemas?',
        'Will live music become rare?',
        'Will festivals grow bigger?',
        'Will people celebrate differently in the future?',
        'Will gift giving change?',
        'Will handmade goods become more valuable?',
        'Will people buy fewer things?',
        'Will sharing replace owning?',
        'Will tourism continue to grow?',
        'Will space travel become common?',
        'Will people live in space?',
        'Will climate change force people to move?',
        'Will cities go underwater?',
        'Will renewable energy replace oil?',
        'Will cars be banned from city centres?',
        'Will walking and cycling become the main ways to move?',
        'Will public transport become free?',
        'Will people fly less?',
        'Will meat consumption fall?',
        'Will people grow their own food more?',
        'Will water become scarce?',
        'Will forests disappear?',
        'Will people recycle more?',
        'Will plastic be banned?',
        'Will fashion become more sustainable?',
        'Will people keep clothes longer?',
        'Will medical technology extend life?',
        'Will people live healthier lives?',
        'Will stress increase?',
        'Will people get enough sleep in the future?',
        'Will mental health care improve?',
        'Will people find more free time?',
        'Will the weekend become longer?',
        'Will people work fewer hours?',
        'Will everyone be connected?',
        'Will privacy disappear?',
        'Will people trust the news less?',
        'Will factual reporting improve?',
        'Will museums go fully digital?',
        'Will libraries close?',
        'Will books become luxury items?',
        'Will people still write letters?',
        'Will handwriting lessons remain?',
        'Will students still take notes?',
        'Will people still watch the news at a fixed time?',
        'Will small shops still exist in big cities?',
        'Will traditional festivals lose their meaning?',
    ]),
    ('Effects / Consequences', [
        'Is online learning as effective as learning in a real classroom?',
        'Is it dangerous for a very young child to use a tablet?',
        'How does unemployment affect a family?',
        "How does pollution affect people's health?",
        'Are large power plants dangerous?',
        'Is childhood today better or worse than before?',
        'Are the streets safer or more dangerous than before?',
        'Does tourism change culture for better or worse?',
        'Do mobile phones make stress worse?',
        'What happens to payments when there is no signal?',
        'What makes a story spread around the world faster than others?',
        "How does city life affect people's health?",
        'What effect does noise have on people?',
        'How does air pollution affect children?',
        'What effect does spending time in nature have?',
        "How does living near a park change people's habits?",
        'What impact does social media have on young people?',
        'How does too much screen time affect sleep?',
        'What effect does watching the news have on mood?',
        'How do video games affect concentration?',
        'What impact does music have on learning?',
        'How does listening to music while studying affect memory?',
        'What effect do festivals have on local business?',
        'How do holidays affect families?',
        'What impact does gift giving have on relationships?',
        'What effect does shopping online have on small shops?',
        "How do sales affect people's spending?",
        'What impact does advertising have on children?',
        'How does fashion affect confidence?',
        'What effect does wearing uniforms have on students?',
        'How does homework affect family time?',
        "What impact do exams have on students' health?",
        'How does competitive sport affect young people?',
        'What effect does regular exercise have on mood?',
        'How does walking affect the brain?',
        'What impact does driving have on the environment?',
        'How does cycling improve a city?',
        'What effect does public transport have on traffic?',
        'How does working from home affect social life?',
        'What impact does remote work have on families?',
        'How does a long commute affect wellbeing?',
        'What effect does overtime have on health?',
        'How does job stress affect family life?',
        'What impact does early retirement have on health?',
        'How does saving money affect happiness?',
        'What effect does debt have on people?',
        'How does living alone change people?',
        'What impact does a big family have on children?',
        'How does having a pet affect stress levels?',
        'What effect do plants have on indoor air?',
        'How does gardening affect mental health?',
        'How does eating out often affect health?',
        'What effect does fast food have on children?',
        'How does skipping breakfast affect concentration?',
        "What impact does sugar have on children's behaviour?",
        'How does street food affect hygiene?',
        'What effect does cooking at home have on a family?',
        'How does learning a language affect the brain?',
        'What impact does reading have on vocabulary?',
        'How does writing by hand affect memory?',
        "What effect do screens have on children's eyes?",
        'How does social media affect friendships?',
        'What impact do photos have on memories?',
        'How does taking photos affect the travel experience?',
        'What effect do souvenirs have on memory?',
        'How does tourism affect local culture?',
        'What impact does tourism have on the environment?',
        'How does mass tourism affect old cities?',
        'What effect do crowds have on shoppers?',
        'How does street noise affect city residents?',
        "What impact do skyscrapers have on a city's character?",
        'How does gentrification affect local people?',
        'What effect does moving house have on children?',
        'How does studying abroad affect young people?',
        'What impact does a gap year have on students?',
        'How does doing homework late affect students?',
        'What effect do private lessons have on other students?',
        'How does exam pressure affect teenagers?',
        'What impact does music education have on children?',
        'How does compulsory art affect creativity?',
        'What effect do school meals have on children?',
        'How does breakfast affect school performance?',
        'What impact does having a garden have on a family?',
        'How does owning a dog affect daily routine?',
        'What effect does walking a dog have on health?',
        'How does pet ownership affect loneliness?',
        'What impact does keeping fish have on children?',
        'How does farming affect wildlife?',
        'What effect does plastic have on oceans?',
        'How does recycling affect the environment?',
        'What impact do cars have on air quality?',
        'How does heat affect city dwellers?',
        'What effect does rain have on city life?',
        'How does extreme weather affect the economy?',
        'How do natural disasters affect communities?',
        'What effect does remote learning have on students?',
        'How does online learning affect discipline?',
        'How does watching subtitles affect language learning?',
        'What impact does translation technology have on learning languages?',
        "How does noise affect students' work at home?",
    ]),
    ('Problem / Solution', [
        'How can schools reduce exam pressure?',
        'How can universities prepare students for real jobs?',
        'Should governments protect minority languages?',
        'Are people taught how to protect themselves online?',
        'How can governments create more jobs?',
        'How can a family save without sacrificing fun?',
        'Is climate change the biggest problem of this century?',
        'How can children be taught to live more greenly?',
        'How can the use of plastic be cut down in a year?',
        'What should the transport of the future look like?',
        'Should the government encourage life in the countryside?',
        'What are the problems of mass tourism?',
        'How can tourists help protect the places they visit?',
        'How can busy families find time for each other?',
        'How can younger people learn from the old?',
        'How can schools encourage every child to exercise?',
        'Does music improve concentration?',
        'How can children be encouraged to read more?',
        'How can society support older workers?',
        'How can we give the elderly respect in a fast society?',
        'Is punishment the best way to prevent crime?',
        'What protects an innocent person from injustice?',
        'How can society reduce stress for young workers?',
        'How can a reader check whether a story is true?',
        'How can families stop throwing food away?',
        'Should countries protect local culture?',
        'How can a country keep its uniqueness in a global world?',
        'How can heritage be protected from time and the storm?',
        'How can cities cut unnecessary water waste?',
        'Should a short afternoon rest be protected in workplaces?',
        'Should prevention come before cure?',
        'How can young people practise interviews?',
        'Do flexible start times improve work?',
        'Should shops close on Sundays to reduce crowds?',
        'What can be done about traffic in big cities?',
        'How can cities reduce air pollution?',
        'What can the government do about housing costs?',
        'How can young people afford homes?',
        'What can be done about loneliness in cities?',
        'How can we encourage people to exercise more?',
        'What should be done about unhealthy eating?',
        'How can we reduce food waste?',
        'What can schools do to reduce exam stress?',
        'How can parents help children sleep more?',
        'What can be done about screen addiction?',
        'How can we make social media safer for children?',
        'What should be done about online scams?',
        "How can we protect people's privacy online?",
        'How can companies reduce data misuse?',
        'What can be done about noise pollution?',
        'How can cities create more green spaces?',
        'What can be done about overcrowded public transport?',
        'How can we make streets safer?',
        'What should be done about potholes and broken pavements?',
        'How can we encourage people to recycle?',
        'What can be done about plastic waste?',
        'How can governments reduce water waste?',
        'What should be done about climate change?',
        'How can we protect endangered animals?',
        'What can be done about stray animals in cities?',
        'How can we reduce noise from construction?',
        'What can be done about litter in parks?',
        'How can we improve food hygiene in markets?',
        'What should be done about food prices?',
        'How can we reduce the cost of living?',
        'What can employers do to reduce stress?',
        'How can people balance work and life?',
        'What can be done about long commutes?',
        'How can companies support remote workers?',
        'What should be done about unemployment among young people?',
        'How can we make jobs more meaningful?',
        'What can be done about low wages?',
        'How can schools help students choose careers?',
        'What can be done about bullying in schools?',
        'How should teachers deal with large classes?',
        'What can be done about students who fall behind?',
        'How can we make education more affordable?',
        'What should be done about university fees?',
        'How can we encourage reading among children?',
        'What can be done about libraries losing visitors?',
        'How can we preserve old buildings?',
        'What should be done about mass tourism?',
        'How can cities handle crowds during festivals?',
        'How can we make tourism more sustainable?',
        'What can be done about overtourism?',
        'How can we help tourists protect local culture?',
        'What should be done about souvenir shops selling cheap imports?',
        'How can we reduce noise at night?',
        'What can be done about busy roads near homes?',
        'How can neighbourhoods become friendlier?',
        'How can we encourage neighbours to know each other?',
        'What can be done about elderly people living alone?',
        'How can we support caregivers?',
        'What should be done about hospital waiting times?',
        'How can governments fund better healthcare?',
        'What can be done about mental health care?',
        'How can we reduce stress in modern life?',
        'What can be done about people sleeping too little?',
        'How can we help people quit unhealthy habits?',
        'What should be done about sugary drinks?',
    ]),
]

_bank: list[dict] = []
_used: set[str] = set()
_pt: dict[str, int] = {}


def _mk(part: str, title: str, prompt: str, tip: str, alt: int) -> dict | None:
    key = part + "|" + prompt
    if key in _used or not prompt or len(prompt) < 8:
        return None
    _used.add(key)
    _pt[part] = _pt.get(part, 0) + 1
    return {
        "id": f"lb-speaking-{part.split()[-1]}-{_pt[part]:04d}",
        "type": "speaking-cue",
        "typeLabel": part,
        "title": title,
        "context": "",
        "prompt": prompt,
        "options": [],
        "correctAnswer": "",
        "explanation": "Answer directly, add a reason, and give one small example. Avoid one-word answers.",
        "logic": "1. Structure your answer: point, reason, example. 2. For Part 2, follow the four bullet points. 3. For Part 3, treat it as a mini-essay: claim, support, conclusion.",
        "tip": tip,
        "suggestions": "Practise the same question again aloud, adding one more reason or example each time.",
        "bandAdvice": "One band rise follows one focused fix: keep answering, keep linking, keep a steady rhythm.",
    }


def build() -> list[dict]:
    if _bank:
        return list(_bank)

    # Part 1 - exactly 100 per category = 700
    for cat, qs in _P1:
        n = sum(1 for x in _bank if x["typeLabel"] == "Part 1")
        for q in qs:
            if sum(1 for x in _bank if x["typeLabel"] == "Part 1") >= n + 100:
                break
            item = _mk("Part 1", f"Part 1 Interview - {cat}", q, _TIPS["Part 1"][sum(1 for x in _bank if x["typeLabel"] == "Part 1") % 3], 0)
            if item:
                item["typeName"] = cat
                _bank.append(item)

    # Part 2 - 25 cards x 4 variants x 6 categories = 600
    _P2_CARD_TYPE = {
        "person": "Person",
        "place": "Place",
        "object": "Object / Thing",
        "event": "Experience / Event",
        "activity": "Activity",
        "future": "Future Plan",
    }
    for cat, cards in _P2_CARDS.items():
        bullets = _P2_BULLETS[cat]
        bi = 0
        for card in cards:
            for _v in range(4):
                b = bullets[(bi := (bi % len(bullets)))]
                bi += 1
                prompt = f"Describe {card}. You should say: {b[0]}, {b[1]}, {b[2]}. and {b[3]}."
                item = _mk("Part 2", f"Part 2 Cue Card - {card}", prompt, _TIPS["Part 2"][sum(1 for x in _bank if x["typeLabel"] == "Part 2") % 3], 1)
                if item:
                    item["typeName"] = _P2_CARD_TYPE.get(cat, "Person")
                    _bank.append(item)

    # Part 3 - exactly 100 per category = 800
    for cat, qs in _P3:
        n = sum(1 for x in _bank if x["typeLabel"] == "Part 3")
        for q in qs:
            if sum(1 for x in _bank if x["typeLabel"] == "Part 3") >= n + 100:
                break
            item = _mk("Part 3", f"Part 3 Discussion - {cat}", q, _TIPS["Part 3"][sum(1 for x in _bank if x["typeLabel"] == "Part 3") % 3], 2)
            if item:
                item["typeName"] = cat
                _bank.append(item)

    return list(_bank)


SPEAKING_LARGE_BANK = build()

SPEAKING_LARGE_BY_TYPE: dict[str, list[dict]] = {}
for _item in SPEAKING_LARGE_BANK:
    SPEAKING_LARGE_BY_TYPE.setdefault(_item["typeLabel"], []).append(_item)

SPEAKING_OFFICIAL_LABELS: dict[str, str] = {
    "Part 1 \u2014 Introduction & Interview (personal questions)": "Part 1",
    "Part 2 \u2014 Cue Card / Individual Long Turn": "Part 2",
    "Part 3 \u2014 Discussion (abstract questions)": "Part 3",
}
for _official, _short in SPEAKING_OFFICIAL_LABELS.items():
    SPEAKING_LARGE_BY_TYPE[_official] = list(SPEAKING_LARGE_BY_TYPE.get(_short, []))
