"""Original IELTS-style Listening question bank.

Organised by official question type. Every item carries the full teaching set
the AI Brain can reveal after evaluation: answer, explanation, logic, tip,
suggestions and band advice. Around 45 hand-written items; Gemini generates
fresh equivalents on top when it is available, so practice volume is
effectively unlimited ("~500 questions or AI-generated equivalents").
"""

from typing import Any

LISTENING_QUESTION_TYPES = [
    "Multiple Choice",
    "Matching",
    "Map / Plan / Diagram Labelling",
    "Form Completion",
    "Note Completion",
    "Table Completion",
    "Flow-chart Completion",
    "Summary Completion",
    "Sentence Completion",
    "Short Answer",
]

# Question types typically used on each official part slot.
PART_TYPES = {
    "Full Listening Section": LISTENING_QUESTION_TYPES,
    "Part 1": ["Form Completion", "Note Completion", "Multiple Choice"],
    "Part 2": ["Map / Plan / Diagram Labelling", "Multiple Choice", "Table Completion"],
    "Part 3": ["Matching", "Multiple Choice", "Sentence Completion", "Short Answer"],
    "Part 4": ["Sentence Completion", "Multiple Choice", "Summary Completion", "Flow-chart Completion"],
    "Quick Practice": ["Multiple Choice", "Form Completion", "Sentence Completion"],
    "Individual Question Types": LISTENING_QUESTION_TYPES,
}

LISTENING_BY_TYPE: dict[str, list[dict[str, Any]]] = {}

Item = dict[str, Any]


def _register(*items: Item) -> None:
    for item in items:
        label = item["typeLabel"]
        LISTENING_BY_TYPE.setdefault(label, []).append(item)


# ---------------------------------------------------------------------------
# Form / Note Completion
# ---------------------------------------------------------------------------

_register(
    {
        "type": "form-completion",
        "typeLabel": "Form / Note Completion",
        "title": "Membership application",
        "context": "Receptionist: Good afternoon, City Fitness. What's your surname? Member: It's Whitaker — W-H-I-T-A-K-E-R. Receptionist: And a contact number? Member: 07981 222 431. Receptionist: Would you prefer the monthly plan or the yearly one? Member: The yearly one is better value, so I'll take that.",
        "prompt": "Surname: ____",
        "options": [],
        "correctAnswer": "Whitaker",
        "explanation": "The member spells his surname directly: W-H-I-T-A-K-E-R.",
        "logic": "1. Listen for 'surname'. 2. The next words include the spelling. 3. Copy exactly what is spelled — do not guess from pronunciation.",
        "tip": "Spelled names are the most common form questions. Write the letters as you hear them.",
        "suggestions": "Practise listening to surname/email/postcode spellings and writing them immediately in capital letters.",
        "bandAdvice": "Error-free name and number capture is a Band 6 baseline skill; it usually reveals spelling slips under 6.5.",
    },
    {
        "type": "form-completion",
        "typeLabel": "Form / Note Completion",
        "title": "Phone number",
        "context": "Advisor: Your mobile number, please. Student: It's 07700 900 214. Advisor: Was that 07700 900 2-1-4? Student: That's right.",
        "prompt": "Mobile: ____",
        "options": [],
        "correctAnswer": "07700 900 214",
        "explanation": "The number is stated and then repeated by the advisor, confirming 07700 900 214.",
        "logic": "1. Expect a correction pattern. 2. The second version spoken by the advisor confirms the digits. 3. Use the confirmed version.",
        "tip": "Numbers are usually said twice — the repeated (confirmed) version is the safe one.",
        "suggestions": "Write numbers in groups as you hear them; never wait for the end of the conversation.",
        "bandAdvice": "Instant number capture during audio is essential from Band 6 upward; pause exercises build it.",
    },
    {
        "type": "form-completion",
        "typeLabel": "Form / Note Completion",
        "title": "Date of birth",
        "context": "Clerk: Could I take your date of birth? Caller: The fourteenth of March, 1992. Clerk: So 14, 03, 1992. Caller: Yes, exactly.",
        "prompt": "Date of birth: ____",
        "options": [],
        "correctAnswer": "14/03/1992",
        "explanation": "The caller says 'the fourteenth of March, 1992' and the clerk confirms 14, 03, 1992.",
        "logic": "1. They announce a date field. 2. The ordinal 'fourteenth' maps to the day number 14. 3. The confirmation standardises the format day/month/year.",
        "tip": "Write dates in a fixed format (DD/MM/YYYY) so you never lose the order.",
        "suggestions": "Practise converting ordinals (fourteenth) to numerals instantly in dictation exercises.",
        "bandAdvice": "Ordinal-to-number conversion is a core Band 5.5-6 task; it becomes automatic with focused drills.",
    },
    {
        "type": "form-completion",
        "typeLabel": "Form / Note Completion",
        "title": "Email address",
        "context": "Assistant: And the email address? Visitor: It's j.odonnell at mail dot com. That's j dot o'donnell. Assistant: Thank you.",
        "prompt": "Email: ____",
        "options": [],
        "correctAnswer": "j.odonnell@mail.com",
        "explanation": "The visitor spells j dot o'donnell at mail dot com — the apostrophe is part of the address.",
        "logic": "1. Fill the field as it is dictated. 2. Reproduce the dot, the apostrophe and '@'. 3. Do not add a space after the dot.",
        "tip": "For emails, copy dots and apostrophes exactly. 'At' becomes '@' and 'dot' becomes '.'.",
        "suggestions": "Dictate emails to yourself and write them without listening again until you get three in a row correct.",
        "bandAdvice": "Precise copying of dictated text separates Band 6 from Band 7 for form tasks.",
    },
    {
        "type": "note-completion",
        "typeLabel": "Form / Note Completion",
        "title": "Accommodation preferences",
        "context": "Agent: Which area do you prefer? Student: Somewhere close to campus, ideally within walking distance. Agent: And the budget? Student: Under four hundred a month if possible.",
        "prompt": "Area: close to ____  Maximum rent: ____",
        "options": [],
        "correctAnswer": "campus / £400",
        "explanation": "The student wants 'close to campus' and 'under four hundred a month'.",
        "logic": "1. Note the two fields: area and budget. 2. 'Close to campus' fills the area. 3. 'Under four hundred' is the budget ceiling; keep the format consistent (£400).",
        "tip": "Answer note fields in keywords, not full sentences — the word limit only allows the essentials.",
        "suggestions": "Practise turning spoken preferences into two or three keyword notes before the next question.",
        "bandAdvice": "Keyword note-taking is a Band 6.5-7 strategy; writing full sentences loses time that solid notes save.",
    },
    {
        "type": "form-completion",
        "typeLabel": "Form / Note Completion",
        "title": "Library fine",
        "context": "Librarian: This book is three weeks late, so the fine is two pounds fifty. Student: Oh, I only have a note. Librarian: That's fine — you can pay at the counter machines too.",
        "prompt": "Fine amount: ____",
        "options": [],
        "correctAnswer": "£2.50",
        "explanation": "The librarian states the fine as 'two pounds fifty', i.e. £2.50.",
        "logic": "1. Listen for a money phrase. 2. 'Two pounds fifty' maps to £2.50. 3. The second sentence is about payment method, not the amount.",
        "tip": "Money answers are stated once in the target sentence — do not let the next sentence distract you.",
        "suggestions": "Practise prices in pounds and pence so 'two fifty' instantly means £2.50.",
        "bandAdvice": "Listening for a single data point among speech is a Band 6 skill; distractors usually arrive right after the answer.",
    },
    {
        "type": "note-completion",
        "typeLabel": "Form / Note Completion",
        "title": "Course enrolment notes",
        "context": "Advisor: The module runs Wednesday evenings, and assessment is one essay and a group presentation. Tutor: Also they can join the reading group if they want extra support.",
        "prompt": "Day: ____  Assessment: essay + ____",
        "options": [],
        "correctAnswer": "Wednesday / group presentation",
        "explanation": "The advisor says the module runs on Wednesday evenings and assessment is one essay and a group presentation.",
        "logic": "1. Two gaps: day and assessment. 2. 'Wednesday evenings' fills the day. 3. 'One essay and a group presentation' fills the assessment; ignore the reading-group extra.",
        "tip": "Fill gaps in the order they appear on the page; the last sentence often adds optional extras that do not go in a gap.",
        "suggestions": "Practise selective listening: only take what a gap asks for and discard the rest.",
        "bandAdvice": "Answering exactly what the gap asks — no more — protects marks at every band level.",
    },
    {
        "type": "form-completion",
        "typeLabel": "Form / Note Completion",
        "title": "Booking details",
        "context": "Hotel clerk: How many nights will you stay? Guest: From the fifth to the eighth of June, so three nights. Clerk: A twin room and breakfast? Guest: Yes please.",
        "prompt": "Nights: ____",
        "options": [],
        "correctAnswer": "3",
        "explanation": "The guest works it out: five to eight June is three nights.",
        "logic": "1. The dates are given first. 2. The guest calculates 'so three nights'. 3. Trust the stated result over your own arithmetic.",
        "tip": "Speakers often give the answer after the reasoning word 'so', 'which makes', or 'that means'.",
        "suggestions": "Always write down the computed result the speaker states, even if you counted differently.",
        "bandAdvice": "Catching stated conclusions in fluent fast speech is a Band 7+ listening skill.",
    },
    {
        "type": "form-completion",
        "typeLabel": "Form / Note Completion",
        "title": "Postcode",
        "context": "Clerk: And the postcode of the new address? Caller: It's MK7 3HY. Clerk: MK7 3HY, thank you.",
        "prompt": "Postcode: ____",
        "options": [],
        "correctAnswer": "MK7 3HY",
        "explanation": "The caller gives MK7 3HY and the clerk repeats it unchanged.",
        "logic": "1. Listen for letters and digits after 'postcode'. 2. Letters are named individually. 3. Copy the exact sequence including the space.",
        "tip": "Postcodes mix letters and numbers — keep the letter case and the space exactly as dictated.",
        "suggestions": "Dictate random postcodes from a list until you can write them first time, every time.",
        "bandAdvice": "Fast, error-free copying of mixed alphanumeric strings is a staple of Band 6+ form questions.",
    },
    {
        "type": "note-completion",
        "typeLabel": "Form / Note Completion",
        "title": "Trip insurance",
        "context": "Agent: What does the policy cover? Caller: Medical costs are covered automatically, but phone and laptop damage needs a separate rider. Agent: Understood.",
        "prompt": "Covered automatically: ____",
        "options": [],
        "correctAnswer": "medical costs",
        "explanation": "Medical costs are covered automatically; phone and laptop damage needs a separate rider.",
        "logic": "1. Match the phrase 'covered automatically'. 2. 'Medical costs are covered automatically' supplies the gap. 3. The extra rider is about other items — not the auto cover.",
        "tip": "Listen for the exact phrase in the prompt ('covered automatically') and take the words attached to it.",
        "suggestions": "Underline the key phrase in each gap so you know the exact words to listen for.",
        "bandAdvice": "Matching prompt phrases to the audio is the core of all completion tasks at Band 6.5.",
    },
)


# ---------------------------------------------------------------------------
# Map Labelling
# ---------------------------------------------------------------------------

_register(
    {
        "type": "map-labelling",
        "typeLabel": "Map Labelling",
        "title": "Where is the library?",
        "context": "Go past the main entrance, turn left at the fountain, and the library is the second building on your right.",
        "prompt": "The library is the second building on the ____ of the fountain.",
        "options": ["left", "right", "opposite", "corner"],
        "correctAnswer": "right",
        "explanation": "After the fountain you turn left and the library is the 'second building on your right'.",
        "logic": "1. Reference point: the fountain. 2. The route says turn left at the fountain. 3. The library is 'on your right' — the answer is the right side.",
        "tip": "Answer where the DESTINATION sits relative to the reference point, not the direction of your turn.",
        "suggestions": "Trace routes on real campus maps with a finger while listening to directions in English.",
        "bandAdvice": "Direction language (left/right/opposite/beyond) is a Band 6 baseline map skill.",
    },
    {
        "type": "map-labelling",
        "typeLabel": "Map Labelling",
        "title": "Museum entrance",
        "context": "The ticket desk is opposite the main doors. Turn right as you enter and the coatroom is immediately in front of you at the far wall.",
        "prompt": "Ticket desk: ____ the main doors.  Coatroom: far wall on the ____",
        "options": ["opposite", "left", "right", "beside"],
        "correctAnswer": "opposite / right",
        "explanation": "The ticket desk is 'opposite the main doors'; the coatroom is 'immediately in front of you' after turning right.",
        "logic": "1. Map the first landmark: ticket desk opposite the doors. 2. Route: enter, turn right. 3. Coatroom is straight ahead at the far wall → it is on the right side entered.",
        "tip": "Break the route at 'as you enter' — everything before it locates the first building, everything after locates the next.",
        "suggestions": "Draw mini-maps from spoken directions to turn language into spatial images.",
        "bandAdvice": "Splitting a route into before/after entry points is a Band 6.5 map strategy.",
    },
    {
        "type": "map-labelling",
        "typeLabel": "Map Labelling",
        "title": "University sports centre",
        "context": "The swimming pool is behind the main building, past the lake, and the changing rooms attach to its western side. The gym is directly above them on the top floor.",
        "prompt": "Swimming pool: ____ the main building.  Changing rooms: ____ side of the pool.",
        "options": ["behind", "east", "in front of", "western"],
        "correctAnswer": "behind / western",
        "explanation": "The pool is 'behind the main building' and the changing rooms are on 'its western side'.",
        "logic": "1. 'Behind the main building' fixes the pool. 2. 'Its western side' fixes the changing rooms — 'its' = the pool's. 3. Match each option to the landmark stated in the map key.",
        "tip": "Pronouns (its, they, the building) tell you which landmark the next item belongs to.",
        "suggestions": "Underline the landmark each label asks about before the audio starts.",
        "bandAdvice": "Tracking pronoun reference under listening pressure is a Band 7 map skill.",
    },
    {
        "type": "map-labelling",
        "typeLabel": "Map Labelling",
        "title": "Town hall tour",
        "context": "The council chamber is to the north of the main hall. Cross the courtyard, and the archive room sits opposite the chamber, across from the gift shop. The toilets are next to the gift shop on the same side.",
        "prompt": "Archive room: ____ the council chamber.  Toilets: ____ the gift shop.",
        "options": ["opposite", "north of", "next to", "south of"],
        "correctAnswer": "opposite / next to",
        "explanation": "The archive room is 'opposite the chamber'; the toilets are 'next to the gift shop'.",
        "logic": "1. Floor one: chamber north of the hall. 2. 'Archive room sits opposite the chamber' — answer opposite. 3. 'Toilets are next to the gift shop' — answer next to.",
        "tip": "If two numbers follow in sequence ('opposite the X, next to the Y'), read each relative to its own landmark.",
        "suggestions": "Practise pairs of location clues so one landmark naming does not cross-fill the next gap.",
        "bandAdvice": "Sequential location clues test working memory; it is a classic Band 6.5-7 question.",
    },
    {
        "type": "map-labelling",
        "typeLabel": "Map Labelling",
        "title": "Farm park route",
        "context": "Start at the entrance. The sheep shed is immediately on the left. Carry on past the pond, then the goat pen is on the right just before the woodland walk begins.",
        "prompt": "Sheep shed: ____ of the entrance.  Goat pen: right, ____ the woodland walk.",
        "options": ["left", "before", "after", "behind"],
        "correctAnswer": "left / before",
        "explanation": "The sheep shed is 'immediately on the left' of the entrance; the goat pen is on the right 'just before the woodland walk'.",
        "logic": "1. 'Immediately on the left' locates the sheep shed. 2. Route: past the pond to the goat pen. 3. 'Just before the woodland walk' — before is correct.",
        "tip": "'Just before X' locates a place immediately prior to X on the route, not after it.",
        "suggestions": "Map questions reward tracing: keep your pen following the route as the audio moves.",
        "bandAdvice": "Route-tracing under real time-pressure separates Band 6 from Band 7 map takers.",
    },
    {
        "type": "map-labelling",
        "typeLabel": "Map Labelling",
        "title": "Hotel lobby",
        "context": "The restaurant is on the ground floor at the back. The lift is opposite the reception desk. If you need the meeting rooms, they are on the first floor directly above the restaurant.",
        "prompt": "Restaurant: ground floor, at the ____  Lift: ____ the reception desk.",
        "options": ["back", "opposite", "front", "beside"],
        "correctAnswer": "back / opposite",
        "explanation": "The restaurant is 'at the back' of the ground floor and the lift is 'opposite the reception desk'.",
        "logic": "1. 'At the back' fixes the restaurant. 2. 'Opposite the reception desk' fixes the lift. 3. The meeting-room sentence adds vertical detail, not location.",
        "tip": "Listen for the second landmark before locking in the lift's position.",
        "suggestions": "Do map labelling with the map covered once, then compare — it trains true listening.",
        "bandAdvice": "Earlier options are often planted first; confirm each against its exact relative phrase.",
    },
    {
        "type": "map-labelling",
        "typeLabel": "Map Labelling",
        "title": "Science centre",
        "context": "The planetarium entrance is straight ahead as you come in, through the glass doors. The café is to the left of the entrance, and the exhibition hall is right beside the café.",
        "prompt": "Planetarium: ____ ahead.  Café: ____ of the entrance.  Exhibition hall: beside the ____",
        "options": ["straight", "left", "café", "right"],
        "correctAnswer": "straight / left / café",
        "explanation": "The planetarium is straight ahead; the café is to the left of the entrance; the exhibition hall is beside the café.",
        "logic": "1. 'Straight ahead as you come in' fixes the planetarium. 2. 'To the left of the entrance' fixes the café. 3. 'Right beside the café' fixes the hall — beside the café.",
        "tip": "Three labels in one audio segment: write each answer the moment its relative phrase is heard.",
        "suggestions": "Sequence-drill three-item map clips until instant capture is comfortable.",
        "bandAdvice": "Handling multiple labels per segment is expected above Band 6 diagonal.",
    },
    {
        "type": "map-labelling",
        "typeLabel": "Map Labelling",
        "title": "Airport terminal",
        "context": "Check-in desks are in the centre. The security gate is beyond them on the way to the gates, and the duty-free shops line the corridor after security.",
        "prompt": "Security: ____ the check-in desks.  Duty-free: ____ the corridor after security.",
        "options": ["beyond", "before", "lining", "in"],
        "correctAnswer": "beyond",
        "explanation": "Security is 'beyond' the check-in desks on the way to the gates.",
        "logic": "1. Check-in desks in the centre. 2. 'Beyond them' — them = check-in desks. 3. Security is beyond the desks; the shops line the corridor.",
        "tip": "'Beyond them' is a one-word answer planted right after the desks are named — stay with it.",
        "suggestions": "Listen for 'them' / 'these' to know which landmark is being measured from.",
        "bandAdvice": "Short, late answers are typical; losing focus after clear early info costs Band points.",
    },
)


# ---------------------------------------------------------------------------
# Multiple Choice
# ---------------------------------------------------------------------------

_register(
    {
        "type": "multiple-choice",
        "typeLabel": "Multiple Choice",
        "title": "Why does the student call?",
        "context": "Student: I missed the enrolment deadline, but I was abroad. Could I still join the photography course? Advisor: Enrolment has closed, but the waiting list is open.",
        "prompt": "Why does the student call?",
        "options": ["To change courses", "To ask about a late enrolment", "To cancel a booking", "To complain"],
        "correctAnswer": "To ask about a late enrolment",
        "explanation": "The student missed the enrolment deadline and asks whether they can still join — a late enrolment.",
        "logic": "1. Read the question: why the call. 2. The student states the problem (missed deadline). 3. The question then is 'can I still join' = late enrolment. 4. Other options are not mentioned.",
        "tip": "Listen for the REASON stated by the speaker, not just repeated words — distractors repeat heard words.",
        "suggestions": "Predict the reason before the audio; match speaker intent, not vocabulary.",
        "bandAdvice": "Distinguishing reason from repeated detail is the core Band 6.5 MC skill.",
    },
    {
        "type": "multiple-choice",
        "typeLabel": "Multiple Choice",
        "title": "Preferred course time",
        "context": "Tutor: Would mornings or evenings suit you better? Student: Mornings clash with my lab class. Evenings are free, but the night bus is unreliable, so maybe Wednesday afternoons? Tutor: That works.",
        "prompt": "The student prefers classes on ____",
        "options": ["Mornings", "Evenings", "Wednesday afternoons", "The weekend"],
        "correctAnswer": "Wednesday afternoons",
        "explanation": "Mornings clash with the lab, evenings have an unreliable bus, so the student settles on Wednesday afternoons.",
        "logic": "1. Track every option as it is rejected. 2. Mornings: clash. 3. Evenings: bad bus. 4. The final 'so maybe' — settled choice — is the answer.",
        "tip": "After a chain of rejections, the answer is the option introduced by 'so', 'then', or 'instead'.",
        "suggestions": "Write two letters per rejected option (X) as you hear reasoning against it.",
        "bandAdvice": "Ruling out by listening to reasons is exactly what IELTS tests at Band 6.5-7.",
    },
    {
        "type": "multiple-choice",
        "typeLabel": "Multiple Choice",
        "title": "Main topic of the lecture",
        "context": "Professor: Today we move from insect behaviour to pollinator decline. Surprisingly, the biggest driver is habitat fragmentation, not pesticide use as most assume.",
        "prompt": "What is the main topic of the lecture?",
        "options": ["The benefits of pesticides", "Pollinator decline and its main cause", "How to build insect habitats", "The history of agriculture"],
        "correctAnswer": "Pollinator decline and its main cause",
        "explanation": "The professor announces the topic as pollinator decline and corrects the assumed cause to habitat fragmentation.",
        "logic": "1. The opening tells the topic: pollinator decline. 2. 'The biggest driver is…' introduces the cause. 3. The option covering topic + cause is correct.",
        "tip": "Openers name the topic; the first correction ('not X as most assume') reveals the thesis.",
        "suggestions": "Choose the option that matches the lecturer's claim, not the common assumption they challenge.",
        "bandAdvice": "Lecture main-idea MCs reward hearing the correction; Band 7+ hinges on it.",
    },
    {
        "type": "multiple-choice",
        "typeLabel": "Multiple Choice",
        "title": "Missing item to bring",
        "context": "Leader: Each team needs a whistle, a stopwatch and a banner. Oh, and someone please bring sunscreen — the forecast is hot. The rest is provided.",
        "prompt": "Which item must the group still bring?",
        "options": ["A whistle", "A stopwatch", "A banner", "Sunscreen"],
        "correctAnswer": "Sunscreen",
        "explanation": "Whistle, stopwatch and banner are provided; sunscreen is the extra asked for.",
        "logic": "1. List provided items: whistle, stopwatch, banner. 2. 'Oh, and someone please bring sunscreen' flags an extra. 3. The extra request is the answer.",
        "tip": "An 'Oh, and…' after a list almost always adds the one thing that is NOT provided.",
        "suggestions": "Distinguish provided vs requested words; write P for provided, R for required.",
        "bandAdvice": "Negation + addition detection is a Band 6 skill with high scoring frequency.",
    },
    {
        "type": "multiple-choice",
        "typeLabel": "Multiple Choice",
        "title": "The tutor's recommendation",
        "context": "Student: Should I take the statistics module or the data one? Tutor: Given your goal, statistics is more relevant, but the data module fits your timetable better. I'd choose data for now.",
        "prompt": "What does the tutor recommend?",
        "options": ["The statistics module", "The data module", "Neither module", "Both modules"],
        "correctAnswer": "The data module",
        "explanation": "The tutor weighs relevance vs timetable but concludes 'I'd choose data for now'.",
        "logic": "1. Two candidates, two pros. 2. The recommendation keyword 'I'd choose' follows. 3. The choice text = the answer.",
        "tip": "Options may both be praised; only the final 'I'd choose…' decides the answer.",
        "suggestions": "When two options seem valid, wait for the decision word ('I'd choose', 'better to'.)",
        "bandAdvice": "Holding attention through praise to reach a decision is a Band 7 MC requirement.",
    },
    {
        "type": "multiple-choice",
        "typeLabel": "Multiple Choice",
        "title": "Reason for the change",
        "context": "Announcement: The Wednesday workshop moves to Thursday. This is because the guest speaker can only attend midweek, and the room was already booked Friday.",
        "prompt": "Why was the workshop moved?",
        "options": ["The room was too small", "The speaker's availability changed", "Students requested it", "Friday was a public holiday"],
        "correctAnswer": "The speaker's availability changed",
        "explanation": "The workshop moves because the guest speaker can only attend midweek.",
        "logic": "1. The shift is announced. 2. 'This is because…' introduces the cause. 3. Speaker availability is the stated cause; Friday booking is a secondary detail.",
        "tip": "After 'this is because' or 'due to', the first reason given is normally the answer.",
        "suggestions": "Practise cause-and-effect listening; distinguish primary cause from secondary constraint.",
        "bandAdvice": "Primary-versus-secondary cause reasoning appears regularly at Band 6.5.",
    },
    {
        "type": "multiple-choice",
        "typeLabel": "Multiple Choice",
        "title": "Speaker's overall view",
        "context": "Speaker: Local museums are often dismissed as old-fashioned. But I think they do more for neighbourhood identity than any new development could.",
        "prompt": "What is the speaker's view of local museums?",
        "options": ["They are outdated", "They are undervalued", "They cost too much", "They are overrated"],
        "correctAnswer": "They are undervalued",
        "explanation": "Many dismiss museums as old-fashioned, but the speaker believes they help identity enormously — so undervalued.",
        "logic": "1. Others' view: old-fashioned. 2. The contrast 'But I think' flips it. 3. The claim of huge value → undervalued.",
        "tip": "Contrast markers ('but', 'however', 'while many say') carry the speaker's true position.",
        "suggestions": "Match the option to the speaker's claim, not the opposing popular view.",
        "bandAdvice": "Detecting attitude in short spoken extracts is tested right up to Band 8.",
    },
    {
        "type": "multiple-choice",
        "typeLabel": "Multiple Choice",
        "title": "What the student forgot",
        "context": "Student: I brought my laptop and notes, but left my student card at home. Professor: You'll need it to borrow the reference books.",
        "prompt": "Which item does the library require?",
        "options": ["The laptop", "The notes", "The student card", "The reference book"],
        "correctAnswer": "The student card",
        "explanation": "The library requires the student card to borrow books; it was left at home.",
        "logic": "1. Items present: laptop, notes. 2. Missing item: student card. 3. Professor confirms a requirement tied to the missing card.",
        "tip": "When a needed item is missing, the required thing is usually the missing one.",
        "suggestions": "Connect 'need' to 'forgot' — they usually point at the same item.",
        "bandAdvice": "Connecting requirements to missing possessions is a standard Band 6 MC move.",
    },
    {
        "type": "multiple-choice",
        "typeLabel": "Multiple Choice",
        "title": "Destination recommendation",
        "context": "Agent: Brighton is lively but pricey. Dover is cheaper yet quieter. Given your budget and wish for nightlife, Brighton fits better.",
        "prompt": "Which destination does the agent recommend?",
        "options": ["Brighton", "Dover", "London", "Nowhere in particular"],
        "correctAnswer": "Brighton",
        "explanation": "The agent weighs cost and atmosphere and concludes Brighton 'fits better' for budget plus nightlife.",
        "logic": "1. Brighton: lively, pricey. 2. Dover: cheaper, quieter. 3. The criteria (budget + nightlife) favour Brighton → 'fits better'.",
        "tip": "Match the recommendation to the stated criteria, not to the cheapest option.",
        "suggestions": "Write the two criteria, then assign each option one point until a winner appears.",
        "bandAdvice": "Weighted-criteria choice questions are classic Band 7 MCs.",
    },
)


# ---------------------------------------------------------------------------
# Matching
# ---------------------------------------------------------------------------

_register(
    {
        "type": "matching",
        "typeLabel": "Matching",
        "title": "Who said what",
        "context": "Amir: The rigid schedule is the issue. Priya: For me it's the cost of materials. Tom: Actually, I'd say the location puts people off more than anything.",
        "prompt": "Match each person to their main concern.  Amir: ____  Priya: ____  Tom: ____",
        "options": ["Cost of materials", "The location", "The rigid schedule", "The staff"],
        "correctAnswer": "Amir → The rigid schedule; Priya → Cost of materials; Tom → The location",
        "explanation": "Amir names the schedule, Priya the cost, and Tom the location as the main issues.",
        "logic": "1. Track who speaks first. 2. Amir → schedule. 3. Priya → cost. 4. Tom → location. 5. Write each letter as its speaker finishes.",
        "tip": "Match during the audio: write the letter next to each name the moment it is stated.",
        "suggestions": "Fill the name column first, then the issue column each time a new speaker talks.",
        "bandAdvice": "Simultaneous tracking of speaker and content is a Band 7 matching skill.",
    },
    {
        "type": "matching",
        "typeLabel": "Matching",
        "title": "Facility problems",
        "context": "Student: The gym is fine but the pool is always at capacity. Friend: Really? I found the study rooms noisy, though the café was okay. Student: Either way, parking remains a true nightmare.",
        "prompt": "Match the person to the problem they mention.  Student (first): ____  Friend: ____",
        "options": ["The pool capacity", "Noisy study rooms", "The cost", "Parking"],
        "correctAnswer": "Student (first) → The pool capacity; Friend → Noisy study rooms",
        "explanation": "The student mentions pool capacity; the friend mentions noisy study rooms.",
        "logic": "1. First student: pool at capacity. 2. Friend: study rooms noisy. 3. The final parking line broadens, but match by who stated what.",
        "tip": "Place each stated problem beside the name that said it; ignore later summaries.",
        "suggestions": "Match one-to-one; if an option repeats a topic, still tie it to the first speaker.",
        "bandAdvice": "Precise speaker-to-content mapping is central to Band 6.5+ matching.",
    },
    {
        "type": "matching",
        "typeLabel": "Matching",
        "title": "Research opinions",
        "context": "Dr. Khan: Diet outweighs exercise for weight control. Dr. Lee: I would stress the reverse — exercise is the more reliable lever. Dr. Obi: Both matter, but genetics decides the outcome.",
        "prompt": "Match each doctor to their view.  Dr. Khan: ____  Dr. Lee: ____  Dr. Obi: ____",
        "options": ["Exercise is more reliable", "Diet outweighs exercise", "Genetics decides", "Neither matters"],
        "correctAnswer": "Dr. Khan → Diet outweighs exercise; Dr. Lee → Exercise is more reliable; Dr. Obi → Genetics decides",
        "explanation": "Each doctor states an opinion; Khan favours diet, Lee favours exercise, Obi says genetics decides.",
        "logic": "1. Khan: diet first. 2. Lee: 'the reverse' = exercise. 3. Obi: 'both matter, but genetics'. 4. Anchor each answer to its speaker's exact claim.",
        "tip": "'The reverse' means the opposite of the previous claim — check the prior option.",
        "suggestions": "Cross out used options as each speaker is matched to avoid reuse confusion.",
        "bandAdvice": "Tracing contrarian expressions ('the reverse', 'not necessarily') builds Band 7 matching.",
    },
    {
        "type": "matching",
        "typeLabel": "Matching",
        "title": "Item photos needed",
        "context": "Photographer: I need a close-up of the clock mechanism, a wide shot of the hall, and for the exhibit leaflet, a detail of the stained glass. Can you grab them today? Assistant: I'll start with the clock.",
        "prompt": "Match each output to the subject.  Close-up: ____  Wide shot: ____  Leaflet detail: ____",
        "options": ["The clock mechanism", "The hall", "The stained glass", "The map"],
        "correctAnswer": "Close-up → The clock mechanism; Wide shot → The hall; Leaflet detail → The stained glass",
        "explanation": "The photographer pairs the close-up with the clock, the wide shot with the hall, and the leaflet detail with the stained glass.",
        "logic": "1. 'A close-up of X' — X is the subject. 2. 'A wide shot of Y' — Y the next. 3. 'A detail of Z' — Z the last. 4. Match type to subject as listed.",
        "tip": "Each output word is attached to its subject by 'of'; copy the pair directly.",
        "suggestions": "Practise three-item matching in a single audio burst until all three are captured.",
        "bandAdvice": "Multi-item matching within one segment is standard across Band 6-8.",
    },
    {
        "type": "matching",
        "typeLabel": "Matching",
        "title": "Volunteer roles",
        "context": "Manager: Sara, could you handle the refreshments? Ben, you're on registration. And for entry control, let's have Omar at the main gate. Priya, you'll float between areas.",
        "prompt": "Match each volunteer to their role.  Sara: ____  Ben: ____  Omar: ____",
        "options": ["Refreshments", "Registration", "Entry control", "Cleaning"],
        "correctAnswer": "Sara → Refreshments; Ben → Registration; Omar → Entry control",
        "explanation": "Sara gets refreshments, Ben registration, and Omar entry control at the main gate.",
        "logic": "1. Each name is followed by a role phrase. 2. 'You're on X' = role X. 3. Record at first mention; Priya's floating role is not an option target.",
        "tip": "'You're on __' and 'you'll handle __' are role signals; follow each name closely.",
        "suggestions": "Listen for the name first, then hold on for its role phrase.",
        "bandAdvice": "Role-assignment matching favours those who write names then roles as they arrive.",
    },
    {
        "type": "matching",
        "typeLabel": "Matching",
        "title": "Course feedback pairs",
        "context": "First student: The reading list was the strongest part. Second student: I found the seminars overlong. Third student: For me, the assessment brief was confusing.",
        "prompt": "Match each student to what they praised or criticised.  Reading list: ____  Seminars: ____  Assessment brief: ____",
        "options": ["Strongest part", "Overlong", "Confusing", "Helpful"],
        "correctAnswer": "Reading list → Strongest part; Seminars → Overlong; Assessment brief → Confusing",
        "explanation": "The reading list was praised as strongest; seminars were overlong; the assessment brief was confusing.",
        "logic": "1. Listen for the subject phrase, then its adjective. 2. Pair each course feature with its descriptor. 3. Ignore softening words like 'for me'.",
        "tip": "Match feature-to-description in the order the speaker lists them.",
        "suggestions": "Practise noun-adjective pair capture in short feedback extracts.",
        "bandAdvice": "Simple noun-adjective matching lives in every band; speed makes the difference above 7.",
    },
    {
        "type": "matching",
        "typeLabel": "Matching",
        "title": "Who runs which society",
        "context": "President: The debate society is run by Mika, the photography club by Jamal, and after some reshuffling, the hiking group now belongs to Elena.",
        "prompt": "Match each society to its leader.  Debate: ____  Photography: ____  Hiking: ____",
        "options": ["Mika", "Jamal", "Elena", "Noah"],
        "correctAnswer": "Debate → Mika; Photography → Jamal; Hiking → Elena",
        "explanation": "Mika runs debate, Jamal runs photography, and Elena now runs hiking after a change.",
        "logic": "1. 'Is run by X' pairs society to leader. 2. Note the change signal 'after reshuffling' — new leader for hiking. 3. Match the final leader listed.",
        "tip": "Change signals ('now', 'after a reshuffle') update an earlier-match — prefer the newer leader.",
        "suggestions": "Treat reshuffle words as hints that the last match printed is the correct one.",
        "bandAdvice": "Handling updates mid-match is a Band 7 nuance in matching tasks.",
    },
    {
        "type": "matching",
        "typeLabel": "Matching",
        "title": "Transport to each venue",
        "context": "Coordinator: For the stadium, take the shuttle. The concert hall is easiest by tram, and for the convention centre the express bus is quickest.",
        "prompt": "Match each venue to the transport.  Stadium: ____  Concert hall: ____  Convention centre: ____",
        "options": ["Shuttle", "Tram", "Express bus", "On foot"],
        "correctAnswer": "Stadium → Shuttle; Concert hall → Tram; Convention centre → Express bus",
        "explanation": "The shuttle serves the stadium, the tram the concert hall, and the express bus the convention centre.",
        "logic": "1. Venue then transport: 'for the stadium, take the shuttle'. 2. Repeat for each venue. 3. Record immediately.",
        "tip": "'For X, take Y' pairs the venue with its mode instantly.",
        "suggestions": "Drill 'for X, Y' structures until the pair jumps out without translation.",
        "bandAdvice": "Rapid pairing of repeated sentence frames is a Band 6+ processing skill.",
    },
    {
        "type": "matching",
        "typeLabel": "Matching",
        "title": "Speaker attitude scale",
        "context": "Panel: On the recycling law, Nina strongly supports it, Ravi has clear reservations, and Sam is entirely neutral on the matter.",
        "prompt": "Match the attitude to each panel member.  Nina: ____  Ravi: ____  Sam: ____",
        "options": ["Strongly supports", "Has reservations", "Neutral", "Opposes fiercely"],
        "correctAnswer": "Nina → Strongly supports; Ravi → Has reservations; Sam → Neutral",
        "explanation": "Nina strongly supports the law, Ravi has reservations, and Sam is neutral.",
        "logic": "1. Three attitudes, three names. 2. 'Nina strongly supports' → match. 3. 'Ravi has clear reservations'. 4. 'Sam is entirely neutral'.",
        "tip": "Attitude words (supports / reservations / neutral) carry the match — listen for them over the subject.",
        "suggestions": "Build attitude vocabulary banks (supports, objects, favours, doubts) for faster matching.",
        "bandAdvice": "Attitude vocabulary is a Band 7 lexical asset for matching questions.",
    },
)


# ---------------------------------------------------------------------------
# Sentence Completion
# ---------------------------------------------------------------------------

_register(
    {
        "type": "sentence-completion",
        "typeLabel": "Sentence Completion",
        "title": "Lecture on sleep",
        "context": "Lecturer: Contrary to expectation, dreaming is most vivid during REM sleep, when the brain clears temporary information to make room for new learning.",
        "prompt": "Dreaming is most vivid during ____ sleep.",
        "options": [],
        "correctAnswer": "REM",
        "explanation": "The lecturer states dreaming is most vivid during REM sleep.",
        "logic": "1. Read the sentence gap. 2. 'Dreaming is most vivid during REM sleep' fills the gap. 3. Copy the exact word REM; do not paraphrase.",
        "tip": "Completion answers must match the recording word-for-word within the word limit.",
        "suggestions": "Practise exact-copy completion; paraphrase loses the mark.",
        "bandAdvice": "Exact matching to the audio keeps Band 6+ completion marks secure.",
    },
    {
        "type": "sentence-completion",
        "typeLabel": "Sentence Completion",
        "title": "Student services",
        "context": "Advisor: The careers office is open at nine, and the counsellor's drop-in hours are Wednesday afternoons. Most students, however, book ahead to guarantee a slot.",
        "prompt": "The counsellor's drop-in hours are on ____ afternoons.",
        "options": [],
        "correctAnswer": "Wednesday",
        "explanation": "The counsellor's drop-in hours are Wednesday afternoons.",
        "logic": "1. Find the day word in the audio. 2. 'Drop-in hours are Wednesday afternoons' — gap equals Wednesday. 3. Booking-ahead detail is not the gap.",
        "tip": "Underline the asked field (day/time) in the sentence so you listen for the right detail.",
        "suggestions": "Predict the word type before listening — here a day name — then capture the first match.",
        "bandAdvice": "Predict-then-capture is the benchmark strategy for Band 6.5 completion.",
    },
    {
        "type": "sentence-completion",
        "typeLabel": "Sentence Completion",
        "title": "Museum visit",
        "context": "Guide: The Roman gallery opens at ten, but the special exhibition opens half an hour later. The café is on the lower floor next to the cloakroom.",
        "prompt": "The special exhibition opens at ____.",
        "options": [],
        "correctAnswer": "10:30",
        "explanation": "The Roman gallery opens at ten and the exhibition half an hour later, i.e. 10:30.",
        "logic": "1. Note the base time: ten. 2. 'Half an hour later' → 10:30. 3. Do not confuse the café/else where detail.",
        "tip": "'Half an hour later' after a stated time means +30 minutes; do the arithmetic instantly.",
        "suggestions": "Practise time arithmetic (later/earlier/by) so it is instant in the exam.",
        "bandAdvice": "Time-calculation completions reward automatic number sense from Band 6.",
    },
    {
        "type": "sentence-completion",
        "typeLabel": "Sentence Completion",
        "title": "Research methods",
        "context": "Professor: We began with surveys, but the response rate was poor, so we switched to interviews and supplemented them with direct observation.",
        "prompt": "The team switched from surveys to ____, supplemented by observation.",
        "options": [],
        "correctAnswer": "interviews",
        "explanation": "Surveys were replaced by interviews, supported by direct observation.",
        "logic": "1. Start: surveys. 2. 'Switched to interviews' — the new method. 3. 'Supplemented by observation' explains support, not the switch target.",
        "tip": "'Switched to X' names the replacement; 'supplemented by Y' names an extra, not the replacement.",
        "suggestions": "Separate replacement words from supplementary words in your notes (R vs S).",
        "bandAdvice": "Disentangling replaced vs supported methods is a Band 7 listening task.",
    },
    {
        "type": "sentence-completion",
        "typeLabel": "Sentence Completion",
        "title": "Library opening changes",
        "context": "Announcer: From next month the library will close at eight on Fridays instead of six, and the weekend hours stay the same.",
        "prompt": "From next month the library closes at ____ on Fridays.",
        "options": [],
        "correctAnswer": "8 (eight)",
        "explanation": "The Friday closing time changes from six to eight next month.",
        "logic": "1. The change target: Friday closing. 2. 'Close at eight instead of six' — new time is eight. 3. Weekend hours are unchanged, not the answer.",
        "tip": "'X instead of Y' means the new value is X; the old value Y is a distractor.",
        "suggestions": "Rewrite 'instead of' pairs as new/old in your notes during the audio.",
        "bandAdvice": "'Instead of' correction listening is a Band 6 staple with recurring distractor risk.",
    },
    {
        "type": "sentence-completion",
        "typeLabel": "Sentence Completion",
        "title": "Gardening advice",
        "context": "Expert: Most tomato growers water daily, but in clay soils watering every other day produces bigger fruit because the roots are forced deeper.",
        "prompt": "In clay soils, watering ____ produces bigger fruit.",
        "options": [],
        "correctAnswer": "every other day",
        "explanation": "In clay soils, watering every other day produces bigger fruit as roots go deeper.",
        "logic": "1. The condition: clay soils. 2. 'Watering every other day produces bigger fruit' — the gap is the watering frequency. 3. Daily watering is the contrast, not the answer.",
        "tip": "The gap following a condition ('in clay soils') is answered by the phrase attached to that condition.",
        "suggestions": "Track condition → behaviour → result to place each phrase correctly.",
        "bandAdvice": "Conditional reasoning in listening is part of Band 7 academic-style completion.",
    },
    {
        "type": "sentence-completion",
        "typeLabel": "Sentence Completion",
        "title": "Train timetable",
        "context": "Announcer: The 9:15 to the city centre is delayed by twenty minutes. Passengers should take the 9:40 which is on time.",
        "prompt": "The 9:15 train is delayed by ____ minutes.",
        "options": [],
        "correctAnswer": "20",
        "explanation": "The 9:15 is delayed by twenty minutes; passengers should take the 9:40.",
        "logic": "1. Fact: 9:15 delayed. 2. 'Delayed by twenty minutes' fills the gap. 3. The 9:40 suggestion is alternative travel, not the delay.",
        "tip": "Delay arithmetic should match the stated 'delayed by X' — do not add the suggestion train.",
        "suggestions": "Write 'delayed by' plus the number and ignore route alternatives for the gap.",
        "bandAdvice": "Accurate single-event capture amid announcements is a Band 6 core skill.",
    },
    {
        "type": "sentence-completion",
        "typeLabel": "Sentence Completion",
        "title": "Health talk",
        "context": "Speaker: Compared with moderate walking, interval running raises heart-rate recovery more effectively, yet beginners often find the walking version easier to sustain for months.",
        "prompt": "Compared with walking, ____ running improves heart-rate recovery more.",
        "options": [],
        "correctAnswer": "interval",
        "explanation": "Interval running raises heart-rate recovery more effectively than moderate walking.",
        "logic": "1. Comparison: walking vs running. 2. 'Interval running raises… more effectively' supplies the gap word. 3. The ease comment is about the other option.",
        "tip": "Comparison listenings place the answer next to the comparative ('more', 'better', 'faster').",
        "suggestions": "Hear the comparative marker and capture the noun immediately before it.",
        "bandAdvice": "Comparative sweep is a recurring Band 7 completion move.",
    },
    {
        "type": "sentence-completion",
        "typeLabel": "Sentence Completion",
        "title": "Island ferry",
        "context": "On Saturdays the first ferry leaves at seven, and the last one at nine at night. Between them, boats run every hour on the hour.",
        "prompt": "On Saturdays the last ferry leaves at ____ pm.",
        "options": [],
        "correctAnswer": "9 (nine)",
        "explanation": "The last Saturday ferry leaves at nine at night, i.e. 9 pm.",
        "logic": "1. Two facts: first at seven, last at nine. 2. The gap asks for the last departure → nine. 3. The hourly schedule is context, not the answers.",
        "tip": "When a sentence gives first and last, note both—the question selects one.",
        "suggestions": "Practise first/last schedule pairs so selecting either is instant.",
        "bandAdvice": "Selecting between paired facts is a routine Band 6 completion decision.",
    },
    {
        "type": "sentence-completion",
        "typeLabel": "Sentence Completion",
        "title": "Club funding",
        "context": "The arts club received a grant of five hundred pounds, but the equipment alone cost seven hundred, so the shortfall will be covered by ticket sales and a bake sale.",
        "prompt": "The club's shortfall will be covered by ticket sales and a ____ sale.",
        "options": [],
        "correctAnswer": "bake",
        "explanation": "The shortfall is covered by ticket sales and a bake sale.",
        "logic": "1. Shortfall sources: ticket sales and a bake sale. 2. The gap precedes 'sale', so its content is the fundraiser name: bake. 3. Do not place the equipment figure in the gap.",
        "tip": "List-type completions give the answer inside a pair ('ticket sales and a bake sale').",
        "suggestions": "Complete pairs in the order they are listed and copy the exact noun.",
        "bandAdvice": "Exact pair capture supports Band 6+ accuracy on money-related tasks.",
    },
)


# ---------------------------------------------------------------------------

# Quick mix for the short mode: one item per core type.
QUICK_MIX = [
    LISTENING_BY_TYPE["Multiple Choice"][0],
    LISTENING_BY_TYPE["Form / Note Completion"][0],
    LISTENING_BY_TYPE["Sentence Completion"][0],
    LISTENING_BY_TYPE["Matching"][0],
]


_TYPED_ALIASES = {
    "Form Completion": "Form / Note Completion",
    "Note Completion": "Form / Note Completion",
    "Table Completion": "Form / Note Completion",
    "Flow-chart Completion": "Form / Note Completion",
    "Summary Completion": "Form / Note Completion",
    "Short Answer": "Short Answer",
    "Map / Plan / Diagram Labelling": "Map Labelling",
}


def items_for_type(type_label: str) -> list[Item]:
    items = list(LISTENING_BY_TYPE.get(type_label, []))
    if not items and type_label in _TYPED_ALIASES:
        items = list(LISTENING_BY_TYPE.get(_TYPED_ALIASES[type_label], []))
    return items


def mixed_items() -> list[Item]:
    flat: list[Item] = []
    for type_label in LISTENING_QUESTION_TYPES:
        flat.extend(items_for_type(type_label))
    return flat


def items_for_mode(mode: str) -> list[Item]:
    """Official-style item pool for a listening mode (part slot or type)."""
    if mode in LISTENING_QUESTION_TYPES:
        return items_for_type(mode)
    if mode == "Quick Practice":
        return QUICK_MIX
    types = PART_TYPES.get(mode, LISTENING_QUESTION_TYPES)
    flat: list[Item] = []
    for type_label in types:
        flat.extend(items_for_type(type_label))
    return flat